---
title: "Comparing LUCA runs for station all"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(plotly)
library(lubridate)
library(knitr)
library(kableExtra)
library(dataRetrieval)
library(hydroGOF)
library(sp)
library(raster)
library(sf)
library(mapview)
library(here)
library(scales)
library(dataRetrieval)
library(tmap)
library(ggpubr)
library(gridExtra)
library(stringr)

```

# KGE from calibrations

12 station all runs

- KGE mean is 0.86
- Standard deviation is 0.007


```{r}

kge <- read_csv('/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/cals/compare_luca_runs/kge_compare.csv') %>%
  filter(!cal == 'statn_all1')

ggplot(kge, aes(as.character(run), kge)) + geom_point() + labs(x='Station all run')

```

# Unburned parameters

## Scatter plots

```{r read in params, echo = FALSE, message = FALSE, warning = FALSE, include = F}

setwd("/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/cals/compare_luca_runs")

#pull in all filenames with composite
filenames <- list.files('.', pattern=".csv", full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 11)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes) #remove dataframes list

```

```{r, fig.width = 10}
# function to read files, remove top rows, paste site name
read_cals <- function(df, name){
    df <- df %>%
      slice(-c(1:9, 146:277)) %>%
      separate(Parameter, c("Parameter", "value"), sep = ",") %>%
      drop_na() %>%
      dplyr::select(-1) %>% 
      mutate(cal = name)
    

}

#statn_all1 <- read_cals(statn_all1., name = 'statn_all1')
statn_all2 <- read_cals(statn_all2., name = 'statn_all2')
statn_all3 <- read_cals(statn_all3., name = 'statn_all3')
statn_all4 <- read_cals(statn_all4., name = 'statn_all4')
statn_all5 <- read_cals(statn_all5., name = 'statn_all5')
statn_all6 <- read_cals(statn_all6., name = 'statn_all6')
statn_all7 <- read_cals(statn_all7., name = 'statn_all7')
statn_all8 <- read_cals(statn_all8., name = 'statn_all8')
statn_all9 <- read_cals(statn_all9., name = 'statn_all9')
statn_all10 <- read_cals(statn_all10, name = 'statn_all10')
statn_all11 <- read_cals(statn_all11, name = 'statn_all11')
statn_all12 <- read_cals(statn_all12, name = 'statn_all12')

statn <- bind_rows(#statn_all1, 
                   statn_all2, statn_all3, statn_all4, statn_all5,
                  statn_all6, statn_all7, statn_all8, statn_all9, statn_all10,
                  statn_all11, statn_all12) %>%
  # mutate(input_data = 'grid') %>%
  # mutate(year_missing_almost = gsub('grid_', '', cal)) %>%
  # mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
  # dplyr::select(-c(year_missing_almost)) %>%
  rename(param = Parameter) %>%
  filter(!param == 'locGrw',
         !param == 'tempRes')

params <- statn %>%
  filter(!param %in% c('angstrom_a', 'angstrom_b', 
                      'Beta_min', 
                      'Beta_rsd', "Beta_trans", 'clat', 
                      'delayNitrification',
                      'denitrificationRateCoefficient', 
                      'denitrificationSoilSaturationThreshold',
                      'deposition_factor', 'drrad', 
                      'drspac', 'initLPS', 'initRG1',
                      'initRG2', 'Ksink', 'LExCoef', 
                      'longTZ', 'N_concRG1', 'N_concRG2', 'N_delay_RG1',
                      'N_delay_RG2', 
                      'nitrificationSoilTemperatureThreshold', 
                      'nitrificationSurfaceTemperatureThreshold',
                      'opti', 'piadin', 'rootfactor', 'sceno', 
                      'soilImpGT80', 'soilImpLT80',
                      'soilLinRed', 'soilMaxPerc', 'temp_lag')) %>%
    mutate(value = as.numeric(value),
         param = as.factor(param))

limits <- read_csv('/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/cals/param_limits.csv')

params_limits <- left_join(params, limits, by = 'param') %>%
  mutate(param = as.factor(param))


#function to plot all params
plot_params <- function(param_name) {
  params_limits %>%
    filter(param == param_name) %>%
    ggplot(aes(x = cal,
               y = value)) + 
    geom_hline(aes(yintercept = lower), color = 'red') +
    geom_hline(aes(yintercept = upper), color = 'red') + 
    geom_point(size = 3) + 
    ggtitle(param_name) +
    theme_bw()
}

name <- levels(params_limits$param)

lapply(name, plot_params)

```

## Box plots

```{r, fig.width = 10}
# boxplots
plot_params <- function(param_name) {
  # Filter the data for the specific parameter and calculate the standard deviation
  filtered_data <- params %>%
    filter(param == param_name)
  
  stdev_value <- sd(filtered_data$value, na.rm = TRUE)
  
  # Create the plot
  ggplot(filtered_data, aes(x = param, y = value)) + 
    geom_boxplot() +
    ggtitle(param_name) +
    theme_bw() +
    # Add standard deviation as text annotation
    geom_text(aes(label = paste("SD =", round(stdev_value, 2)), 
                  x = 1, 
                  y = max(filtered_data$value, na.rm = TRUE)),
              vjust = -0.5, 
              hjust = 2,
              color = "red")
}
name <- levels(params$param)

lapply(name, plot_params)

```

## Metrics

```{r}

params_summary <- params %>%
  group_by(param) %>%
  summarize(mean = mean(value),
            sd = sd(value),
            cv = sd(value)/mean(value),
            min = min(value),
            max = max(value))


kable(params_summary, digits = 2) %>%
  kable_styling(full_width = F)

```


```{r echo = FALSE, message = FALSE, warning = FALSE, include = F}

setwd("/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/cals/compare_luca_runs")

rm(list = ls())

#pull in all filenames with composite
filenames <- list.files('.', pattern=".csv", full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 11)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes) #remove dataframes list

```

```{r echo = FALSE, message = FALSE, warning = FALSE}

# read in all the grid burn params
read_cals_burn <- function(df, name){
    df <- df %>%
      slice(-c(1:274)) %>%
      separate_wider_delim(Parameter, 
                       delim = ',',
                       names = c('soilID',
                                 'luca_a_rain',
                                 'luca_a_snow',
                                 'luca_soilMaxInfSummer',
                                 'luca_soilMaxDPS',
                                 'luca_lagSurfaceRunoff',
                                 'luca_soilDistMPSLPS')) %>%
      slice(-1) %>%
      dplyr::select(-1) %>% 
      mutate(cal = name)
}

#statn_all1 <- read_cals_burn(statn_all1., name = 'statn_all1')
statn_all2 <- read_cals_burn(statn_all2., name = 'statn_all2')
statn_all3 <- read_cals_burn(statn_all3., name = 'statn_all3')
statn_all4 <- read_cals_burn(statn_all4., name = 'statn_all4')
statn_all5 <- read_cals_burn(statn_all5., name = 'statn_all5')
statn_all6 <- read_cals_burn(statn_all6., name = 'statn_all6')
statn_all7 <- read_cals_burn(statn_all7., name = 'statn_all7')
statn_all8 <- read_cals_burn(statn_all8., name = 'statn_all8')
statn_all9 <- read_cals_burn(statn_all9., name = 'statn_all9')
statn_all10 <- read_cals_burn(statn_all10, name = 'statn_all10')
statn_all11 <- read_cals_burn(statn_all11, name = 'statn_all11')
statn_all12 <- read_cals_burn(statn_all12, name = 'statn_all12')


burn_params <- bind_rows(#statn_all1, 
                         statn_all2, statn_all3, statn_all4, statn_all5,
                  statn_all6, statn_all7, statn_all8, statn_all9, statn_all10,
                  statn_all11, statn_all12) %>%
  ungroup() %>%
  mutate(across(c(luca_a_rain:luca_soilDistMPSLPS), as.numeric)) %>%
  group_by(cal) %>%
  mutate(across(c(luca_a_rain:luca_soilDistMPSLPS), mean)) %>%
  filter(soilID == 22) %>%
  dplyr::select(-soilID) %>% 
  pivot_longer(!cal, 
               names_to = 'params',
               values_to = 'value') %>% 
  mutate(params = str_remove(params, 'luca_')) %>%
  mutate(params = as.factor(params),
         burn = 'yes') 
  

```

# Burned parameters

## Burned scatter plots

```{r echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}

burn_limits <- read_csv('/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/cals/burn_param_limits.csv')

burn_params_limits <- left_join(burn_params, burn_limits, by = 'params') %>%
  mutate(params = as.factor(params))


plot_burnparams <- function(param_name) {
  burn_params_limits %>%
    filter(params == param_name) %>%
    ggplot(aes(y = value,
               x = cal)) +
    geom_hline(aes(yintercept = lower), color = 'red') +
    geom_hline(aes(yintercept = upper), color = 'red') + 
    geom_point(size = 3) +
    ggtitle(param_name) +
    theme_bw()
}

name2 <- levels(burn_params_limits$params)

lapply(name2, plot_burnparams)

```

## Burned box plots

```{r echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
# boxplots
plot_burnparams <- function(param_name) {
  # Filter the data for the specific parameter and calculate the standard deviation
  filtered_data <- burn_params %>%
    filter(params == param_name)
  
  stdev_value <- sd(filtered_data$value, na.rm = TRUE)
  
  # Create the plot
  ggplot(filtered_data, aes(x = params, y = value)) + 
    geom_boxplot() +
    ggtitle(param_name) +
    theme_bw() +
    # Add standard deviation as text annotation
    geom_text(aes(label = paste("SD =", round(stdev_value, 2)), 
                  x = 1, 
                  y = max(filtered_data$value, na.rm = TRUE)),
              vjust = -0.5, 
              hjust = 2,
              color = "red")
}

name2 <- levels(burn_params$params)

lapply(name2, plot_burnparams)

```

## Burned metrics

```{r}

burn_params_summary <- burn_params %>%
  group_by(params) %>%
  summarize(mean = mean(value),
            sd = sd(value),
            cv = sd(value)/mean(value),
            min = min(value),
            max = max(value))


kable(burn_params_summary, digits = 2) %>%
  kable_styling(full_width = F)

```


