---
title: "Fourmile_inputs"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: journal
editor_options: 
  chunk_output_type: console
---

```{r open package, include=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(rmdformats)
library(tidyverse)
library(dplyr)
library(lubridate)
library(plotly)
library(ggplot2)
library(here)
library(scales)
library(here)
library(rgdal)
library(sp)
library(sf)
library(mapview)
library(kableExtra)
library(dataRetrieval)
library(raster)
library(sf)
library(stringr)
library(hydroGOF)
library(Metrics)
library(ranger)
library(missRanger)
library(readxl)

```

```{r loading data, include = F}

setwd('C:/Users/sears/Documents/Repos/fourmile/data/files_to_edit')

#pull in all filenames with csv
filenames <- list.files('.', pattern='.csv', full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 4)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes)

bet_srad <- read_xlsx('bet_srad.xlsx')
updated_prec <- read_xlsx('updated_precip_2016to20.xlsx')
bet_airt <- read_xlsx('bt_Met1.xlsx')
bet_met <-read_xlsx('bt_Met2.xlsx')

```

# RH first

```{r}
#need to bring in Niwot and Betasso and remove prism
rh <- rhum %>%
  mutate(date = dmy(date)) %>%
  dplyr::select(-c(prism_W, prism_M, prism_E))

niwot_rh <- nime %>%
  mutate(date = make_date(Year, Month, Day)) %>%
  dplyr::select(c(date, RH_21m)) %>%
  rename(Niwot = RH_21m) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01')

bet_rh <- bet_met %>%
  rename(rh = 1,
    datetime = 2) %>%
  dplyr::select(c(datetime, rh)) %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(date) %>%
  summarize(rh = mean(rh)) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01') %>%
  rename(Betasso = rh) 

rhall <- full_join(rh, niwot_rh, by = 'date')

rhall <- full_join(rhall, bet_rh, by = 'date') %>% 
  mutate(date = format(as.Date(date), '%d.%m.%Y')) %>%
  replace(is.na(.), -9999)

#rh done
#write.csv(rhall, 'rh_use.csv')

```

# wind 

```{r}
wind <- wind %>%
  mutate(date = dmy(date))

niwot_wind <- nime %>%
  mutate(date = make_date(Year, Month, Day)) %>%
  dplyr::select(c(date, ws_21m)) %>%
  rename(Niwot = ws_21m) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01')

bet_wind <- bet_met %>%
  rename(windspeed = 3,
    datetime = 4) %>%
  dplyr::select(c(datetime, windspeed)) %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(date) %>%
  summarize(wind = mean(windspeed)) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01') %>%
  rename(Betasso = wind) 

windall <- full_join(wind, niwot_wind, by = 'date')

windall <- full_join(windall, bet_wind, by = 'date') %>% 
  mutate(date = format(as.Date(date), '%d.%m.%Y')) %>%
  replace(is.na(.), -9999)

#write.csv(windall, 'wind_use.csv')

```

# Tmax 

```{r}
tmax <- tmax %>%
  mutate(date = dmy(date)) %>%
  dplyr::select(-c(prism_W, prism_M, prism_E))

bet_tmax <- bet_airt %>%
    rename(tmax = 3,
    datetime = 4) %>%
  dplyr::select(c(datetime, tmax)) %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(date) %>%
  summarize(tmax = max(tmax)) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01') %>%
  rename(Betasso = tmax) 

tmaxall <- full_join(tmax, bet_tmax, by = 'date') %>%
  mutate(date = format(as.Date(date), '%d.%m.%Y')) %>%
  replace(is.na(.), -9999)

#write.csv(tmaxall, 'tmax_use.csv')

```

# Tmin

```{r}
tmin <- tmin %>%
  mutate(date = dmy(date)) %>%
  dplyr::select(-c(prism_W, prism_M, prism_E))

bet_tmin <- bet_airt %>%
    rename(tmin = 1,
    datetime = 2) %>%
  dplyr::select(c(datetime, tmin)) %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(date) %>%
  summarize(tmin = min(tmin)) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01') %>%
  rename(Betasso = tmin) 

tminall <- full_join(tmin, bet_tmin, by = 'date') %>%
  mutate(date = format(as.Date(date), '%d.%m.%Y')) %>%
  replace(is.na(.), -9999)

write.csv(tminall, 'tmin_use.csv')

```

# Solar rad

```{r}
solar <- solr %>%
  mutate(date = dmy(date)) %>%
  dplyr::select(-c(prism_W, prism_M, prism_E))

niwot_solar <- niwo %>%
  dplyr::select(c(1, 3)) %>%
  filter(date > '2009-12-31') %>%
  filter(date < '2021-01-01') %>%
  rename(Niwot = 2)

bet_solar <- bet_srad %>%
  mutate(date = as.Date(datetime)) %>%
  group_by(date) %>%
  summarize(sw_in_avg_wm2= mean(in_swrad_wm2)) %>%
  filter(date > '2009-12-31') %>%
  mutate(bet_sw_in_mjm2 = (sw_in_avg_wm2 * 86400) / 1000000) %>%
  dplyr::select(-c(sw_in_avg_wm2)) %>%
  rename(Betasso = bet_sw_in_mjm2)

solarall <- full_join(solar, niwot_solar, by = 'date')

solarall <- full_join(solarall, bet_solar, by = 'date') %>% 
  mutate(date = format(as.Date(date), '%d.%m.%Y')) %>%
  replace(is.na(.), -9999)

write.csv(solarall, 'solar_use.csv')

```

# Precip

```{r}

#daily precip
precall <- prec %>%
  mutate(date = dmy(date),
         doy = yday(date)) %>%
  mutate_at(c('Gordon_South', 'Gordon_North',
              'GH', 'LM', 'SE', 'SP', 'ST', 'NADP_SL'),
            ~(ifelse(!doy %in% c(152:258),
                               NA, .))) %>%
  mutate(prism_most_w = prism_W * 0.974,
         prism_little_w = prism_W * 0.026,
         prism_most_m = prism_M * 0.974,
         prism_little_m = prism_M * 0.026,
         prism_most_e = prism_E * 0.974,
         prism_little_e = prism_E * 0.026) %>%
  mutate_at(c('prism_most_w', 'prism_most_m', 'prism_most_e'), list(lead), n = 1) %>%
  mutate(prism_W = prism_most_w + prism_little_w,
         prism_M = prism_most_m + prism_little_m,
         prism_E = prism_most_e + prism_little_e) %>%
  dplyr::select(-c(prism_most_w, prism_little_w,
                   prism_most_m, prism_little_m,
                   prism_most_e, prism_little_e)) %>%
  mutate_at(c('prism_W', 'prism_M', 'prism_E'), ~(ifelse(doy %in% c(152:258),
                                                         NA, .))) %>%
  filter(date > '2009-12-31')

#####################################################################
#get prism shift only for precip (for year round)
prec_orig <- read_csv('precipAll.csv')

prec_prismshift <- prec_orig %>%
  dplyr::select(c(date, prism_W, prism_M, prism_E)) %>%
  mutate(date = dmy(date)) %>%
  mutate(prism_most_w = prism_W * 0.974,
         prism_little_w = prism_W * 0.026,
         prism_most_m = prism_M * 0.974,
         prism_little_m = prism_M * 0.026,
         prism_most_e = prism_E * 0.974,
         prism_little_e = prism_E * 0.026) %>%
  mutate_at(c('prism_most_w', 'prism_most_m', 'prism_most_e'), list(lead), n = 1) %>%
  mutate(prism_W = prism_most_w + prism_little_w,
         prism_M = prism_most_m + prism_little_m,
         prism_E = prism_most_e + prism_little_e) %>%
  dplyr::select(-c(prism_most_w, prism_little_w,
                   prism_most_m, prism_little_m,
                   prism_most_e, prism_little_e)) %>%
  filter(date > '2009-12-31') %>%
  mutate(date = format(as.Date(date), '%d.%m.%Y'))
  
write.csv(prec_prismshift, 'precip_prismshift.csv')
#####################################################

bet_rain <- bet_met %>%
  dplyr::select(c(5,6)) %>%
  rename(Betasso_rain = 1) %>%
  mutate(date = as.Date(DATE_TIME)) %>%
  group_by(date) %>%
  summarize(Betasso = sum(Betasso_rain)) %>%
  filter(date > '2009-12-31')

precall <- full_join(precall, bet_rain, by = 'date')

updated_prec1 <- updated_prec %>%
  mutate_at(c(2,4,6,8,10), ~(ifelse(. > 7, NA, .))) %>%
  mutate_at(c(2,4,6,8,10), ~(.*25.4)) %>%
  rename(GH = 2,
         LM = 4,
         SE = 6,
         SP = 8,
         ST = 10)

gh <- updated_prec1 %>%
  dplyr::select(c(1,2)) %>%
  mutate(date = mdy(GH_date)) %>%
  dplyr::select(-c(1)) %>%
  distinct(date, .keep_all = TRUE) %>%
  arrange(date)

gh_old <- precall %>%
  dplyr::select(c(date, GH)) %>%
  filter(date < '2016-01-01') %>%
  bind_rows(gh_old, gh) %>%
  distinct(date, .keep_all = TRUE)

precall <- precall %>%
  dplyr::select(-c(GH))
  
precall <- full_join(precall, gh_old, by='date')

lm <- updated_prec1 %>%
  dplyr::select(c(3,4)) %>%
  mutate(date = mdy(LM_date)) %>%
  dplyr::select(-c(1)) %>%
  distinct(date, .keep_all = TRUE) %>%
  arrange(date)

lm_old <- precall %>%
  dplyr::select(c(date, LM)) %>%
  filter(date < '2016-01-01') 
  
lm_old <- bind_rows(lm_old, lm) %>%
  distinct(date, .keep_all = TRUE)

precall <- precall %>%
  dplyr::select(-c(LM))
  
precall <- full_join(precall, lm_old, by='date')

se <- updated_prec1 %>%
  dplyr::select(c(5,6)) %>%
  mutate(date = mdy(SE_date)) %>%
  dplyr::select(-c(1)) %>%
  distinct(date, .keep_all = TRUE) %>%
  arrange(date)

se_old <- precall %>%
  dplyr::select(c(date, SE)) %>%
  filter(date < '2016-01-01') 
  
se_old <- bind_rows(se_old, se) %>%
  distinct(date, .keep_all = TRUE)

precall <- precall %>%
  dplyr::select(-c(SE))
  
precall <- full_join(precall, se_old, by='date')

sp <- updated_prec1 %>%
  dplyr::select(c(7,8)) %>%
  mutate(date = mdy(SP_date)) %>%
  dplyr::select(-c(1)) %>%
  distinct(date, .keep_all = TRUE) %>%
  arrange(date)

sp_old <- precall %>%
  dplyr::select(c(date, SP)) %>%
  filter(date < '2016-01-01') 
  
sp_old <- bind_rows(sp_old, sp) %>%
  distinct(date, .keep_all = TRUE)

precall <- precall %>%
  dplyr::select(-c(SP))
  
precall <- full_join(precall, sp_old, by='date')

st <- updated_prec1 %>%
  dplyr::select(c(9,10)) %>%
  mutate(date = mdy(ST_date)) %>%
  dplyr::select(-c(1)) %>%
  distinct(date, .keep_all = TRUE) %>%
  arrange(date)

st_old <- precall %>%
  dplyr::select(c(date, ST)) %>%
  filter(date < '2016-01-01') 
  
st_old <- bind_rows(st_old, st) %>%
  distinct(date, .keep_all = TRUE)

precall <- precall %>%
  dplyr::select(-c(ST))
  
precall <- full_join(precall, st_old, by='date')


prec_final <- precall %>%
  mutate_at(c('GH', 'LM', 'SE', 'SP', 'ST'),
            ~(ifelse(!doy %in% c(152:258),
                               NA, .))) %>%
  filter(date < '2021-01-01') %>%
  mutate(date = format(as.Date(date), '%d.%m.%Y')) %>%
  dplyr::select(-c(doy))

write.csv(prec_final, 'prec_use.csv')  
       
```

# combine all met data together

```{r}

wind <- read_csv('wind_use.csv')
sol <- read_csv('solar_use.csv')
tmin <- read_csv('tmin_use.csv')
tmax <- read_csv('tmax_use.csv')
prec <- read_csv('prec_use.csv')
rh <- read_csv('rh_use.csv')

#put all data frames into list
df_list <- list(prec, sol, tmin, tmax, wind, rh)

#merge all data frames in list
met_all <- df_list %>% 
  reduce(full_join, by='date')

met_all <- met_all %>%  
  mutate(date = dmy(date),
         doy = yday(date)) %>%
  replace(.==-9999, NA) %>%
  filter(date > '2009-12-31')
  

met_fill <- missRanger(met_all, num.trees=1000)



solar <- ggplot(met_fill, aes(x=date)) +
  geom_line(aes(y=Gordon_S_mjm2), color='blue') +
  geom_line(aes(y=Niwot_mjm2), color='red') +
  geom_line(aes(y=Betasso_mjm2), color='orange')


ggplotly(solar)


```


## Update PRISM

```{r}
#bring in all new prism data
setwd('C:/Users/sears/Documents/Repos/fourmile/data/updated_prism')

#pull in all filenames with csv
filenames <- list.files('.', pattern='.csv', full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1,5)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes)


prism <- list(p2010,p2011,p2012,p2013,p2014,p2015,p2016,p2017,p2018,p2019,p2020)

prism_all <- bind_rows(prism) %>%
  rename(ppt_mm = 6, 
         tmin_c = 7,
         tmax_c = 8) %>%
  arrange(Date) %>%
  filter(str_detect(Name, 'prism_7|prism_12|prism_13|prism_14|prism_15|prism_16|prism_17|prism_18|prism_28'))

#break out by variable then can rotate the data
#tmax first
tmax <- prism_all %>%
  dplyr::select(c(Date, Name, tmax_c)) %>%
  pivot_wider(names_from = Name, values_from = tmax_c)
  
write.csv(tmax, 'tmax.csv')
write.csv(prism_all, 'prism_all.csv')

#tmin
tmin <- prism_all %>%
  dplyr::select(c(Date, Name, tmin_c)) %>%
  pivot_wider(names_from = Name, values_from = tmin_c)
  
write.csv(tmin, 'tmin.csv')

#prism precip 
#best case (in winter prism is used, outside of that NA as -9999 PLUS prism shift)
p_bestcase <- prism_all %>%
  dplyr::select(c(Date, Name, ppt_mm)) %>%
  pivot_wider(names_from = Name, values_from = ppt_mm) %>%
  mutate(prism_most_7 = prism_7 * 0.974,
         prism_little_7 = prism_7 * 0.026,
         prism_most_12 = prism_12 * 0.974,
         prism_little_12 = prism_12 * 0.026,
         prism_most_13 = prism_13 * 0.974,
         prism_little_13 = prism_13 * 0.026,
         prism_most_14 = prism_14 * 0.974,
         prism_little_14 = prism_14 * 0.026,
         prism_most_15 = prism_15 * 0.974,
         prism_little_15 = prism_15 * 0.026,
         prism_most_16 = prism_16 * 0.974,
         prism_little_16 = prism_16 * 0.026,
         prism_most_17 = prism_17 * 0.974,
         prism_little_17 = prism_17 * 0.026,
         prism_most_18 = prism_18 * 0.974,
         prism_little_18 = prism_18 * 0.026,
         prism_most_28 = prism_28 * 0.974,
         prism_little_28 = prism_28 * 0.026) %>%
  mutate_at(c('prism_most_7', 'prism_most_12', 'prism_most_13',
              'prism_most_14', 'prism_most_15', 'prism_most_16',
              'prism_most_17', 'prism_most_18', 'prism_most_28'),
            list(lead), n = 1) %>%
  mutate(prism_7 = prism_most_7 + prism_little_7,
         prism_12 = prism_most_12 + prism_little_12,
         prism_13 = prism_most_13 + prism_little_13,
         prism_14 = prism_most_14 + prism_little_14,
         prism_15 = prism_most_15 + prism_little_15,
         prism_16 = prism_most_16 + prism_little_16,
         prism_17 = prism_most_17 + prism_little_17,
         prism_18 = prism_most_18 + prism_little_18,
         prism_28 = prism_most_28 + prism_little_28,) %>%
  dplyr::select(-c(prism_most_7, prism_little_7,
                   prism_most_12, prism_little_12,
                   prism_most_13, prism_little_13,
                   prism_most_14, prism_little_14,
                   prism_most_15, prism_little_15,
                   prism_most_16, prism_little_16,
                   prism_most_17, prism_little_17,
                   prism_most_18, prism_little_18,
                   prism_most_28, prism_little_28)) %>%
  mutate(doy = yday(Date)) %>%
  mutate_at(c('prism_7', 'prism_12', 'prism_13',
              'prism_14', 'prism_15', 'prism_16',
              'prism_17', 'prism_18', 'prism_28'), 
            ~(ifelse(doy %in% c(152:258), -9999, .)))

write.csv(p_bestcase, 'p_bestcase.csv')

p_shift <- prism_all %>%
    dplyr::select(c(Date, Name, ppt_mm)) %>%
  pivot_wider(names_from = Name, values_from = ppt_mm) %>%
  mutate(prism_most_7 = prism_7 * 0.974,
         prism_little_7 = prism_7 * 0.026,
         prism_most_12 = prism_12 * 0.974,
         prism_little_12 = prism_12 * 0.026,
         prism_most_13 = prism_13 * 0.974,
         prism_little_13 = prism_13 * 0.026,
         prism_most_14 = prism_14 * 0.974,
         prism_little_14 = prism_14 * 0.026,
         prism_most_15 = prism_15 * 0.974,
         prism_little_15 = prism_15 * 0.026,
         prism_most_16 = prism_16 * 0.974,
         prism_little_16 = prism_16 * 0.026,
         prism_most_17 = prism_17 * 0.974,
         prism_little_17 = prism_17 * 0.026,
         prism_most_18 = prism_18 * 0.974,
         prism_little_18 = prism_18 * 0.026,
         prism_most_28 = prism_28 * 0.974,
         prism_little_28 = prism_28 * 0.026) %>%
  mutate_at(c('prism_most_7', 'prism_most_12', 'prism_most_13',
              'prism_most_14', 'prism_most_15', 'prism_most_16',
              'prism_most_17', 'prism_most_18', 'prism_most_28'),
            list(lead), n = 1) %>%
  mutate(prism_7 = prism_most_7 + prism_little_7,
         prism_12 = prism_most_12 + prism_little_12,
         prism_13 = prism_most_13 + prism_little_13,
         prism_14 = prism_most_14 + prism_little_14,
         prism_15 = prism_most_15 + prism_little_15,
         prism_16 = prism_most_16 + prism_little_16,
         prism_17 = prism_most_17 + prism_little_17,
         prism_18 = prism_most_18 + prism_little_18,
         prism_28 = prism_most_28 + prism_little_28,) %>%
  dplyr::select(-c(prism_most_7, prism_little_7,
                   prism_most_12, prism_little_12,
                   prism_most_13, prism_little_13,
                   prism_most_14, prism_little_14,
                   prism_most_15, prism_little_15,
                   prism_most_16, prism_little_16,
                   prism_most_17, prism_little_17,
                   prism_most_18, prism_little_18,
                   prism_most_28, prism_little_28))
  

write.csv(p_shift, 'p_shift.csv')

p_noshift <- prism_all %>%
  dplyr::select(c(Date, Name, ppt_mm)) %>%
  pivot_wider(names_from = Name, values_from = ppt_mm)

write.csv(p_noshift, 'p_noshift.csv')

#need to do RH!!!
#RH: =100*(EXP((17.625*TD)/(243.04+TD))/EXP((17.625*T)/(243.04+T)))
#pull in all filenames with csv
filenames <- list.files('.', pattern='.csv', full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1,5)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes)


prismt <- list(t2010,t2011,t2012,t2013,t2014,t2015,t2016,t2017,t2018,t2019,t2020)

rh <- bind_rows(prismt) %>%
  na.omit() %>% 
  rename(tmean_c = 6, 
         tdew_c = 7) %>%
  arrange(Date) %>%
  group_by(Name, Date) %>%
  mutate(rh = 100*(exp((17.625*tdew_c)/(243.04+tdew_c))/exp((17.625*tmean_c)/(243.04+tmean_c)))) %>%
  dplyr::select(c(Date, Name, rh)) %>%
  pivot_wider(names_from = Name, values_from = rh)
  
write.csv(rh, 'rh.csv')


```

