---
title: "Fourmile-Best Runs"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(plotly)
library(hydroGOF)

```

# Performance metrics

```{r}

flow <- read_csv('./best_performance/best_perf_flow.csv') %>%
  mutate(date = mdy(date)) %>%
  replace(.==-9999, NA)

kge <- flow %>%
  drop_na() %>% 
  summarize(KGE_grid2012_grid = KGE(grid2012_grid, obs),
            KGE_grid2012_statn = KGE(grid2012_statn, obs),
            KGE_statn2017_grid = KGE(statn2017_grid, obs),
            KGE_statn2017_statn = KGE(statn2017_statn, obs))


nse <- flow %>%
  drop_na() %>% 
  summarize(NSE_grid2012_grid = NSE(grid2012_grid, obs),
            NSE_grid2012_statn = NSE(grid2012_statn, obs),
            NSE_statn2017_grid = NSE(statn2017_grid, obs),
            NSE_statn2017_statn = NSE(statn2017_statn, obs))

pbias <- flow %>%
  drop_na() %>%
  summarize(pbias_grid2012_grid = pbias(grid2012_grid, obs),
            pbias_grid2012_statn = pbias(grid2012_statn, obs),
            pbias_statn2017_grid = pbias(statn2017_grid, obs),
            pbias_statn2017_statn = pbias(statn2017_statn, obs))

kge_yr <- flow %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarize(KGE_grid2012_grid = KGE(grid2012_grid, obs),
            KGE_grid2012_statn = KGE(grid2012_statn, obs),
            KGE_statn2017_grid = KGE(statn2017_grid, obs),
            KGE_statn2017_statn = KGE(statn2017_statn, obs))

```

# Hydrographs

```{r}

flow_long <- flow %>%
  drop_na() %>%
  pivot_longer(!date,
               names_to = 'run',
               values_to = 'flow_cms')

hydrograph <- ggplot(flow_long,
       aes(x=date,
           y=flow_cms,
           color=run)) +
  geom_line(size = 0.5) +
  theme_bw(base_size=20)


ggplotly(hydrograph)

```

