---
title: "Manuscript figures"
author: "Megan Sears"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(plotly)
library(kableExtra)
library(hydroGOF)
library(here)
library(sf)
library(scales)
library(tmap)
library(ggpubr)
library(gridExtra)
library(stringr)
library(cowplot)

```

# Figure 1

```{r}

# this is a spatial map that was started in R and moved to Arc
# put the paths to files below **

```

# Figure 2

Streamflow and climate overview

4 panel met first

```{r}
# Note, it is OK these are pulling from the sept2013 udpate and not dec2024
# because the climate outputs will not change due to changed  obs streamflow (removed 2013 flood Q)
grid <- read_csv("./38HRU_oct2025_updates/grid_all_Catchment.csv",
                 skip=3) %>%
   slice(3:n()) %>%
  dplyr::select(-starts_with('@'),
                -1) %>%
  mutate(date = ymd(time)) %>%
  dplyr::select(-time) %>%
  mutate_if(is.character, as.numeric) %>% 
  mutate(site = 'grid')

statn <- read_csv('./38HRU_oct2025_updates/statn_all_Catchment.csv',
                 skip=3) %>%
   slice(3:n()) %>%
  dplyr::select(-starts_with('@'),
                -1) %>%
  mutate(date = ymd(time)) %>%
  dplyr::select(-time) %>%
  mutate_if(is.character, as.numeric) %>% 
  mutate(site = 'statn')

all <- bind_rows(grid, statn) %>%
  arrange(date)

catchment_mo_mean <- all %>%
  mutate(month = month(date)) %>%
  group_by(site, month) %>%
  summarise(across(tmean:solRad, ~ mean(.x, na.rm = TRUE))) %>%
  dplyr::select(site, month, tmean_mean = tmean, 
                solrad_mean = solRad, rh_mean = rhum)

# sum is for P only
catchment_mo_sum <- all %>%
  dplyr::select(date, precip, site) %>%
  mutate(month = month(date),
         year = year(date)) %>%
  group_by(month, year, site) %>%
  summarize(p_sum = sum(precip))

catchment_mo_sd <- all %>%
  mutate(month = month(date)) %>%
  group_by(site, month) %>%
  summarise(across(tmean:solRad, ~ sd(.x, na.rm = TRUE))) %>%
  dplyr::select(site, month, tmean_sd = tmean, 
                solrad_sd = solRad, rh_sd = rhum)


catchment_mo <- left_join(catchment_mo_mean, catchment_mo_sd, 
                          by = c('month', 'site'))

catchment_mo <- left_join(catchment_mo, catchment_mo_sum)

catchment_mo2 <- catchment_mo %>%
  mutate(month_name = month.abb[month]) %>%
  mutate(month_name = factor(month_name, 
                             levels = c('Jan', 'Feb', 'Mar',
                                        'Apr', 'May', 'Jun',
                                        'Jul', 'Aug', 'Sep',
                                        'Oct', 'Nov', 'Dec')))
# add month for P
catchment_mo_sum2 <- catchment_mo_sum %>%
  mutate(month_name = month.abb[month]) %>%
  mutate(month_name = factor(month_name, 
                             levels = c('Jan', 'Feb', 'Mar',
                                        'Apr', 'May', 'Jun',
                                        'Jul', 'Aug', 'Sep',
                                        'Oct', 'Nov', 'Dec')))

# changed P to boxplot per TG comment (instead of cols)
p_box <- catchment_mo_sum2 %>% 
  filter(month_name %in% c('Jun','Jul','Aug', 'Sep')) %>%
  ggplot(., aes(x = month_name, y = p_sum, fill = site)) +
  geom_boxplot() +
  ylim(0,150) + # remove the 2013 flood outliers
  scale_fill_manual(values = c("#0047AB", "orange"),
                    labels = c("Gridded", "Station")) +
  theme_bw(base_size = 20) +
  labs(y = 'Precipitation (mm)',
       x = element_blank()) +
    guides(
    fill = guide_legend(
      title = NULL,
      override.aes = list(shape = NA, linetype = 0)  # remove boxplot look on legend
    )) +
    theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.text = element_blank()) 

p_box

# Temperature plot
t_moplot <- ggplot(catchment_mo2, aes(x = month_name, 
                                      y = tmean_mean, 
                                      color = site, 
                                      group = site)) +
  geom_ribbon(aes(ymin = tmean_mean - tmean_sd, 
                  ymax = tmean_mean + tmean_sd, 
                  fill = site), 
              alpha = 0.6) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("#0047AB", "orange"),
                     labels = c("Gridded", "Station")) +
  scale_fill_manual(values = c("#0047AB", "orange"),
                    labels = c("Gridded", "Station")) +
  theme_bw(base_size=20) +
  labs(y = expression("Air temperature " ( degree~C)),
       x = element_blank()) +
  labs(color = NULL, fill = NULL) +
      theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.text = element_blank())

# Solar radiation plot
sol_moplot <- ggplot(catchment_mo2, 
                     aes(x = month_name, y = solrad_mean, 
                                         color = site, group = site)) +
  geom_ribbon(aes(ymin = solrad_mean - solrad_sd, 
                  ymax = solrad_mean + solrad_sd, 
                  fill = site), 
              alpha = 0.6) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("#0047AB", "orange"),
                     labels = c("Gridded", "Station")) +
  scale_fill_manual(values = c("#0047AB", "orange"),
                    labels = c("Gridded", "Station")) +
  theme_bw(base_size = 20) +
  labs(y = expression("Solar radiation (MJ/m"^"2" * ")"),
       x = element_blank()) +
  labs(color = NULL, fill = NULL) +
      theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.text = element_blank())

# Relative humidity plot
rh_moplot <- ggplot(catchment_mo2, 
                    aes(x = month_name, 
                        y = rh_mean, 
                        color = site, 
                        group = site)) +
  geom_ribbon(aes(ymin = rh_mean - rh_sd, 
                  ymax = rh_mean + rh_sd, 
                  fill = site), 
              alpha = 0.6) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c("#0047AB", "orange"),
                     labels = c("Gridded", "Station")) +
  scale_fill_manual(values = c("#0047AB", "orange"),
                    labels = c("Gridded", "Station")) +
  theme_bw(base_size = 20) +
  labs(y = 'RH (%)', x= element_blank()) +
  labs(color = NULL, fill = NULL) +
      theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.text = element_blank())

# pull met panels together
quad <- ggarrange(p_box, 
          t_moplot,
          sol_moplot,
          rh_moplot,
          common.legend = T,
          legend = 'bottom',
          ncol=2,
          nrow=2) 

quad

ggsave("./figures/quad_20250329_timEdits.png", 
       plot = quad, 
       dpi = 600)


```

Add in streamflow to 4 panel met

```{r}

flow <- read_csv('./38HRU_oct2025_updates/discharge_all.csv') %>%
  replace(.==-9999, NA) %>%
  rename(date = time) %>%
  mutate(date = mdy(date)) %>%
  dplyr::select(date, obs) %>%
  mutate(year = year(date),
         DOY = yday(date)) #%>%
  #drop_na(obs)

flow_plot2 <- ggplot(flow, aes(x = date, y = obs)) + 
  geom_line(size = 1.1) +
  theme_bw(base_size = 20) +
  labs(y = 'Discharge (cms)',
         x = element_blank()) +
    scale_x_date(
    date_breaks = "1 year",          # one tick per year
    date_labels = "%Y"               # show only the year
  ) +
   theme(
    legend.position = "none",
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.text = element_text(color = "black"))

flow_plot2

ggsave("./figures/flow_obs_plot2_eachyrlabel.png", 
       dpi = 600, 
       width = 12, 
       height = 4, 
       units = "in")

# stats for manuscript text
# annual total flow
flowTotYr <- flow %>%
  group_by(year) %>%
  summarize(flow_tot = sum(obs, na.rm=T))

flowTotYr <- flow %>%
  group_by(year) %>%
  summarize(flow_tot = mean(obs, na.rm=T))

flowTotYr <- flow %>%
  group_by(year) %>%
  summarize(flow_tot = max(obs, na.rm=T))

avgAllYr <- mean(flowTotYr$flow_tot)

```

Add together streamflow and 4 panel met

```{r}

# add streamflow to the top of the met 4 panel
quad_plus <- ggarrange(
  flow_plot2, 
  quad,
  nrow = 2,
  heights = c(1, 2)   # first row gets 1 part, second gets 2 parts
)

quad_plus

ggsave("./figures/figure2.png", 
       plot = quad_plus, 
       dpi = 600,
       width = 14,
       height = 12,
       bg='white')

```

# Figure 3

```{r}

# get HRU shp for maps
hru_new <- st_read('./data/GIS/hrus_final.shp')

# grid first
read_ages_grid <- function(filename){
  read_csv(file.path("./38HRU_oct2025_updates/HRU_output/grid/", 
                     filename), skip = 3) %>%
  slice(3:n()) %>%
  dplyr::select(-starts_with('@'),
                -1) %>%
  mutate(time = ymd(time)) %>%
  mutate_if(is.character, as.numeric) %>%
  mutate(source = 'grid')

}

#pull in all filenames with HRU in the name
filenames <- list.files("./38HRU_oct2025_updates/HRU_output/grid/", 
                        pattern="HRU", 
                        full.names=F)

#read all the csvs using read_ages function
dataframes <- lapply(filenames, read_ages_grid)

#name all the csvs based on first 6 characters
names(dataframes) <- substr(filenames, 1, 6)

#bind all and make 1 df
hru_grids <- dataframes %>%
  bind_rows()

# statn next
read_ages_statn <- function(filename){
  read_csv(file.path("./38HRU_oct2025_updates/HRU_output/statn/", 
                     filename), skip = 3) %>%
  slice(3:n()) %>%
  dplyr::select(-starts_with('@'),
                -1) %>%
  mutate(time = ymd(time)) %>%
  mutate_if(is.character, as.numeric) %>%
  mutate(source = 'statn')

}

#pull in all filenames with HRU in the name
filenames <- list.files("./38HRU_oct2025_updates/HRU_output/statn/", 
                        pattern="HRU", 
                        full.names=F)

#read all the csvs using read_ages function
dataframes <- lapply(filenames, read_ages_statn)

#name all the csvs based on first 6 characters
names(dataframes) <- substr(filenames, 1, 6)

#bind all and make 1 df
hru_statn <- dataframes %>%
  bind_rows()

# Tmean
hru_grid_tmean <- hru_grids %>%
  dplyr::select(c(time, ID, tmean)) %>%
  rename(tmean_grid = tmean)  %>%
  group_by(ID) %>%
  summarize(tmean_all_grid = mean(tmean_grid))

hru_statn_tmean <- hru_statn %>%
  dplyr::select(c(time, ID, tmean)) %>%
  rename(tmean_statn = tmean) %>%
  group_by(ID) %>%
  summarize(tmean_all_statn = mean(tmean_statn))

tmean_hrus <- left_join(hru_grid_tmean, hru_statn_tmean, by = c('ID')) %>%
  mutate(diff = tmean_all_statn - tmean_all_grid) %>%
  rename(value = ID)

hrus_map_tmean <- left_join(hru_new, tmean_hrus, by = 'value')

# Cumulative p
hru_grid_precip <- hru_grids %>%
  dplyr::select(c(time, ID, precip)) %>%
  rename(precip_grid = precip)

hru_statn_precip <- hru_statn %>%
  dplyr::select(c(time, ID, precip)) %>%
  rename(precip_statn = precip)

precip_hrus <- left_join(hru_grid_precip, hru_statn_precip, by = c('time', 'ID')) %>%
  mutate(diff = precip_statn - precip_grid,
         year = year(time)) %>%
  group_by(year, ID) %>%
  mutate(total_diff = cumsum(diff)) %>%
  filter(time == max(time)) %>%
  group_by(ID) %>%
  summarize(precip_avg_cumdiff = mean(total_diff)) %>%
  rename(value = ID)

hrus_map_precip <- left_join(hru_new, precip_hrus, by = 'value')

# Solar rad
hru_grid_solrad <- hru_grids %>%
  dplyr::select(c(time, ID, solRad)) %>%
  rename(solrad_grid = solRad)  %>%
  group_by(ID) %>%
  summarize(solrad_all_grid = mean(solrad_grid))

hru_statn_solrad <- hru_statn %>%
  dplyr::select(c(time, ID, solRad)) %>%
  rename(solrad_statn = solRad) %>%
  group_by(ID) %>%
  summarize(solrad_all_statn = mean(solrad_statn))

solrad_hrus <- left_join(hru_grid_solrad, hru_statn_solrad, by = c('ID')) %>%
  mutate(diff = solrad_all_statn - solrad_all_grid) %>%
  rename(value = ID)

hrus_map_solrad <- left_join(hru_new, solrad_hrus, by = 'value')

# RH
hru_grid_rh <- hru_grids %>%
  dplyr::select(c(time, ID, rhum)) %>%
  rename(rh_grid = rhum)  %>%
  group_by(ID) %>%
  summarize(rh_all_grid = mean(rh_grid))

hru_statn_rh <- hru_statn %>%
  dplyr::select(c(time, ID, rhum)) %>%
  rename(rh_statn = rhum) %>%
  group_by(ID) %>%
  summarize(rh_all_statn = mean(rh_statn))

rh_hrus <- left_join(hru_grid_rh, hru_statn_rh, by = c('ID')) %>%
  mutate(diff = rh_all_statn - rh_all_grid) %>%
  rename(value = ID)

hrus_map_rh <- left_join(hru_new, rh_hrus, by = 'value')

# get the location of the stream gauge
locations <- read_csv('/Users/megansears/Documents/Repos/fourmile/data/GIS/locations_all.csv')

locations <- locations %>%
  st_as_sf(., coords=c('lon','lat'), crs = 4326)

gauge <- locations %>%
  filter(display == 'stream')

# bottom theme for panel fig
bottom_theme <-   theme(
    legend.position = "bottom",
    panel.grid.major = element_blank(),
    legend.key.width = unit(.75, "cm"),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = unit(c(-4, 0, 0, 0), "cm"),
    panel.spacing = unit(0, "lines"))

# top theme for panel fig
top_theme <-   theme(
    legend.position = "bottom",
    panel.grid.major = element_blank(),
    legend.key.width = unit(.75, "cm"),
    panel.grid.minor = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = unit(c(0, 0, -4, 0), "cm"),
    panel.spacing = unit(0, "lines"))

# RH panel
rh <- ggplot() +
  geom_sf(data = hrus_map_rh, aes(fill = diff), color = "black", lwd = 0.2) +
  geom_sf(data=gauge, shape=3, size=2, stroke=2) +
  scale_fill_viridis_c(option = "viridis", name = "RH (%)") +
  theme_bw(base_size=15.5) +
  theme_void() + bottom_theme

rh

# Solar rad panel
sr <- ggplot() +
  geom_sf(data = hrus_map_solrad, aes(fill = diff), color = "black", lwd = 0.2) +
  geom_sf(data=gauge, shape=3, size=2, stroke=2) +
  scale_fill_viridis_c(option = "cividis", name = expression("Srad (MJ/m"^"2" * ")")) +
  theme_bw(base_size=15.5) +
  theme_void() + top_theme

sr

# P panel
precip <- ggplot() +
  geom_sf(data = hrus_map_precip, aes(fill = precip_avg_cumdiff), color = "black", lwd = 0.2) +
  geom_sf(data=gauge, shape=3, size=2, stroke=2) +
  scale_fill_viridis_c(option = "mako", name = "Cumulative P (mm)") +
  theme_bw(base_size=15.5) +
  theme_void() + top_theme

precip

# Tmean panel
tmean <- ggplot() +
  geom_sf(data = hrus_map_tmean, aes(fill = diff), color = "black", lwd = 0.2) +
  geom_sf(data=gauge, shape=3, size=2, stroke=2) +
  scale_fill_viridis_c(option = "plasma", name = "Tmean (°C)",
                       limits = c(-5, 2)) +
  theme_bw(base_size=15.5) +
  theme_void() + bottom_theme

tmean

# add the 4 panels togther
lots <- ggarrange(
  precip, 
  sr, 
  rh, 
  tmean,
  heights = 1)

lots

# add ttile
title <- ggdraw() + 
  draw_label("Difference = Station - Gridded", 
             fontface = "bold", 
             size = 16,
             x = 0,  # left-aligned
             hjust = 0) +
  theme(plot.margin = margin(0, 0, -200,15))  # reduce space between title and plot

# Combine title and the main plot
final_plot <- plot_grid(title, 
                        lots, 
                        ncol = 1, 
                        rel_heights = c(0.05, 1))

final_plot

ggsave(filename = "./figures/figure3_oct25.pdf",
       plot = final_plot,
       dpi = 800,
       bg = 'white',
       width = 12,
       height = 8,
       limitsize = FALSE)

```

# Figure 4

## KGE 

```{r}

# read in KGE values (all_kge also has nse and bias even tho name says otherwise)
flow_plot <- read_csv('./all_kge.csv') %>%
  filter(metric == 'KGE') %>%
  dplyr::select(-metric) %>%
  rename(kge = value)

# split model run to source and year
# create kge bins for fig
flow_plot_updated <- flow_plot %>% 
  mutate(source = case_when(
    grepl("grid", model_run) ~ "grid",
    grepl("statn", model_run) ~ "statn"),
    year_excluded = str_extract(model_run, "\\d{4}$")) %>%
  mutate(year_excluded = if_else(model_run %in% c('gridall',
                                                       'statnall'),
                                  'None', year_excluded)) %>%
  mutate(kge_revise_bins = cut(kge,
                               breaks = c(-Inf, 0.0, 0.2, 0.4, 0.6, 0.8, 1),
                               include.lowest = TRUE,
                               labels = c("< 0.0","0.0-0.2", "0.2-0.4", "0.4-0.6", "0.6-0.8", "> 0.8")))

# facet wrap titles
new_facet_titles <- c(
  "grid" = "Gridded",
  "statn" = "Station"
)

# kge plot
both_kge_plot <- flow_plot_updated %>%
  ggplot(., aes(x = year, 
              y = year_excluded, 
              fill = kge_revise_bins)) +
  geom_tile(color = "white") +
  facet_wrap(~source, labeller = labeller(source = new_facet_titles)) +
   scale_fill_manual(values = c(
    "< 0.0" = "#DCBE9BFF", 
    "0.0-0.2" = "#EFDDCFFF",
    "0.2-0.4" = "#F1F4EEFF",
    "0.4-0.6" = "#72E1E1FF",
    "0.6-0.8" = "#11C2B5FF",
    "> 0.8" = "#009474FF"),
    guide = guide_legend(nrow = 1)) +
    geom_text(aes(label = sprintf("%.2f", kge), 
                color = kge_revise_bins), 
            size = 3) +
  scale_color_manual(values = c(
    "< 0.0"   = "black",
    "0.0-0.2" = "black",
    "0.2-0.4" = "black",
    "0.4-0.6" = "black",
    "0.6-0.8" = "black",
    "> 0.8"   = "white"
  ), 
  guide = "none") +
  theme_bw(base_size=18) +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1)) +
  labs(y = "Year excluded",
       x='Year',
       fill = 'KGE') +
  theme(
    axis.text.x = element_text(angle = 45, 
                               hjust = 1),
    legend.position = 'bottom',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.width = unit(.6, "cm"),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
    legend.margin = margin(t = -8, b = -4, unit = "pt")
  )

both_kge_plot

# ggsave('./figures/kge_heatmap_whiteft.png',
#        dpi=800,
#        width = 10,
#        height = 6)

```

### KGE legend

```{r}

# kge legend
kge_legend <- flow_plot_updated %>%
  ggplot(., aes(x = year, 
              y = year_excluded, 
              fill = kge_revise_bins)) +
  geom_tile(color = "white") +
  facet_wrap(~source, labeller = labeller(source = new_facet_titles)) +
   scale_fill_manual(values = c(
    "< 0.0" = "#DCBE9BFF", 
    "0.0-0.2" = "#EFDDCFFF",
    "0.2-0.4" = "#F1F4EEFF",
    "0.4-0.6" = "#72E1E1FF",
    "0.6-0.8" = "#11C2B5FF",
    "> 0.8" = "#009474FF"),
    guide = guide_legend(ncol = 1)) +
    geom_text(aes(label = sprintf("%.2f", kge), 
                color = kge_revise_bins), 
            size = 3) +
  scale_color_manual(values = c(
    "< 0.0"   = "black",
    "0.0-0.2" = "black",
    "0.2-0.4" = "black",
    "0.4-0.6" = "black",
    "0.6-0.8" = "black",
    "> 0.8"   = "white"
  ), 
  guide = "none") +
  theme_bw(base_size=18) +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1)) +
  labs(y = "Year excluded",
       x='Year',
       fill = 'KGE') +
  theme(
    axis.text.x = element_text(angle = 45, 
                               hjust = 1),
    legend.position = 'right',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.width = unit(.6, "cm"),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
    legend.margin = margin(t = -8, b = -4, unit = "pt")
  )

kge_legend

# Extract the legend
leg <- ggpubr::get_legend(kge_legend)

# Convert to ggplot
leg_gg <- ggpubr::as_ggplot(leg)

# Plot it
print(leg_gg)

ggsave('./figures/figure4_kgeLegend.png',
       dpi=800,
       width = 12,
       height = 8,
       bg = 'white')

```

## Bias

```{r}

pbiasCats <- read_csv('./pbiasCats.csv') #%>%
  #rename(source = input_data)

# plot
both_pbias_plot <- pbiasCats %>%
  ggplot(aes(x = year, 
             y = year_missing, 
             fill = pbiasCat)) +
  geom_tile(color = "white") +
  facet_wrap(~source, labeller = labeller(source = new_facet_titles)) +
   scale_fill_manual(values = c(
    "Unsatisfactory" = "#F1F4EEFF", 
    "Satisfactory" = "#EFDDCFFF",
    "Good" = "#72E1E1FF",
    "Very good" = "#009474FF"
  )) +
  geom_text(aes(label = sprintf("%0.1f", pbias),   # one decimal place
                color = pbiasCat), 
            size = 2.75) +
  scale_color_manual(values = c(
    "Unsatisfactory" = "black",
    "Satisfactory"   = "black",
    "Good"           = "black",
    "Very good"      = "white"
  ), guide = "none") + 
  theme_bw(base_size=18) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = 'bottom',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.width = unit(1, "cm"),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
    legend.margin = margin(t = -8, b = -4, unit = "pt")
  ) +
  labs(y = "Year excluded",
       x = 'Year',
       fill = '% bias')

both_pbias_plot

# ggsave('./figures/pbias_heatmap_whiteft.png',
#        dpi=800,
#        width = 10,
#        height = 6)

```

### Bias legend

```{r}

# plot
bias_leg <- pbiasCats %>%
  ggplot(aes(x = year, 
             y = year_missing, 
             fill = pbiasCat)) +
  geom_tile(color = "white") +
  facet_wrap(~source, labeller = labeller(source = new_facet_titles)) +
scale_fill_manual(
  breaks = c("Very good", "Good", "Satisfactory", "Unsatisfactory"),
  values = c(
    "Unsatisfactory" = "#F1F4EEFF", 
    "Satisfactory"  = "#EFDDCFFF",
    "Good"          = "#72E1E1FF",
    "Very good"     = "#009474FF"
  )
)+
  geom_text(aes(label = sprintf("%0.1f", pbias),   # one decimal place
                color = pbiasCat), 
            size = 2.75) +
  scale_color_manual(values = c(
    "Unsatisfactory" = "black",
    "Satisfactory"   = "black",
    "Good"           = "black",
    "Very good"      = "white"
  ), guide = "none") + 
  theme_bw(base_size=18) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = 'right',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.width = unit(1, "cm"),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
    legend.margin = margin(t = -8, b = -4, unit = "pt")
  ) +
  labs(y = "Year excluded",
       x = 'Year',
       fill = 'Bias')

bias_leg

# Extract the legend
leg <- ggpubr::get_legend(bias_leg)

# Convert to ggplot
leg_gg <- ggpubr::as_ggplot(leg)

# Plot it
print(leg_gg)

ggsave('/Users/megansears/Documents/Repos/fourmile/figures/figure4_biasLegend.png',
       dpi=800,
       width = 12,
       height = 8,
       bg = 'white')

```

## NSE

```{r}

nseCats <- read_csv('./nseCats.csv') #%>%
  #rename(source = input_data)

both_nse_plot <- nseCats %>%
  ggplot(aes(x = year, 
             y = year_missing, 
             fill = nseCat)) +
  geom_tile(color = "white") +
  facet_wrap(~source, labeller = labeller(source = new_facet_titles)) +
  scale_fill_manual(values = c(
    "Unsatisfactory" = "#F1F4EEFF", 
    "Satisfactory"  = "#EFDDCFFF",
    "Good"          = "#72E1E1FF",
    "Very good"     = "#009474FF"
  )) +
  geom_text(aes(label = sprintf("%.2f", nse), color = nseCat), 
            size = 2.75) +
  scale_color_manual(values = c(
    "Unsatisfactory" = "black",
    "Satisfactory"   = "black",
    "Good"           = "black",
    "Very good"      = "white"
  ), guide = "none") +
  theme_bw(base_size=18) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = 'bottom',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.width = unit(1, "cm"),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
    legend.margin = margin(t = -8, b = -4, unit = "pt")
  ) +
  labs(y = "Year excluded",
       x = 'Year',
       fill = 'NSE')

both_nse_plot

# ggsave('./figures/nse_heatmap_both_cats_whiteft.png',
#        dpi=600,
#        width = 10,
#        height = 6)

```

### NSE legend

```{r}

nse_leg <- nseCats %>%
  ggplot(aes(x = year, 
             y = year_missing, 
             fill = nseCat)) +
  geom_tile(color = "white") +
  facet_wrap(~source, labeller = labeller(source = new_facet_titles)) +
scale_fill_manual(
  breaks = c("Very good", "Good", "Satisfactory", "Unsatisfactory"),
  values = c(
    "Unsatisfactory" = "#F1F4EEFF", 
    "Satisfactory"  = "#EFDDCFFF",
    "Good"          = "#72E1E1FF",
    "Very good"     = "#009474FF"
  )
)+
  geom_text(aes(label = sprintf("%.2f", nse), color = nseCat), 
            size = 2.75) +
  scale_color_manual(values = c(
    "Unsatisfactory" = "black",
    "Satisfactory"   = "black",
    "Good"           = "black",
    "Very good"      = "white"
  ), guide = "none") +
  theme_bw(base_size=18) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = 'right',
    legend.text = element_text(size = 14),
    legend.title = element_text(size = 14),
    legend.key.width = unit(1, "cm"),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 10, r = 10, b = 10, l = 10),
    legend.margin = margin(t = -8, b = -4, unit = "pt")
  ) +
  labs(y = "Year excluded",
       x = 'Year',
       fill = 'NSE')

nse_leg

# Extract the legend
leg <- ggpubr::get_legend(nse_leg)

# Convert to ggplot
leg_gg <- ggpubr::as_ggplot(leg)

# Plot it
print(leg_gg)

ggsave('/Users/megansears/Documents/Repos/fourmile/figures/figure4_nseLegend.png',
       dpi=800,
       width = 12,
       height = 8,
       bg = 'white')

```

## Combine

```{r}

# Top plot - KGE
top_plot <- both_kge_plot +
  theme(
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    plot.margin = margin(5, 5, 5, 40)   # add space on the left
  )

# Middle plot - Bias
middle_plot <- both_pbias_plot +
  theme(
    strip.text = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x  = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "none",
    plot.margin = margin(5, 5, 5, 40)   # add space on the left
  )

# Bottom plot - NSE
bottom_plot <- both_nse_plot +
  theme(
    strip.text = element_blank(),
    legend.position = "none",
    plot.margin = margin(5, 5, 5, 40)   # add space on the left
  )

# Combine plots
final_grid <- plot_grid(
  top_plot,
  middle_plot,
  bottom_plot,
  ncol = 1,
  labels = c("a) KGE", "b) Bias", "c) NSE"),
  label_size = 16,
  label_fontface = "bold",
  label_x = -0.03,
  label_y = 1.04,
  rel_heights = c(1.1, 1, 1.2),
  align = "v",
  axis = "l"
) 

final_grid_add <- final_grid +
  theme(plot.margin = margin(20, 5, 5, 5))

final_grid_add
  
ggsave('/Users/megansears/Documents/Repos/fourmile/figures/figure4_main_oct2025.pdf',
       dpi=800,
       width = 10,
       height = 14,
       bg='white')

```

# Figure 5

```{r}

# params area weighted (only for lagSurfaceRunoff, a_rain, a_snow)
params <- read_csv('./38HRU_oct2025_updates/params_weighted_oct2025.csv') %>%
  filter(param %in% c('lagSurfaceRunoff',
                      'a_rain',
                      'a_snow')) %>% # select params in the top 8 sens that are area weighted
  rename(value = area_weighted_average,
         input_data = source) %>%
  dplyr::select(param, input_data, year_missing, value)

# params unburned (above is params that needed to be area weighted bc burn/unburn)
params_unburn <- read_csv('./38HRU_oct2025_updates/params_unburn.csv') %>%
  filter(param %in% c('soilOutLPS',
                      'snow_trs',
                      'lagInterflow',
                      'baseTemp',
                      't_factor',
                      'soilLatVertLPS')) %>%
  dplyr::select(param, input_data, year_missing, value) %>%
  mutate(year_missing = if_else(year_missing == 'none',
                                'all',
                                year_missing))

# join the two to get the top 8 sensitve params
param_sens <- bind_rows(params, params_unburn) %>% 
  mutate(input_data = if_else(input_data == 'grid',
                              'Gridded',
                              'Station'))

# read in pbias categories
pbias <- read_csv('./38HRU_oct2025_updates/pbiasCats.csv') %>%
  filter(year == c('All')) %>%
  dplyr::select(source, year_missing, pbias)

nse <- read_csv('./38HRU_oct2025_updates/nseCats.csv') %>%
  filter(year == c('All')) %>%
  dplyr::select(source, year_missing, nse)

perf <- left_join(nse, pbias, by = c('source',
                                     'year_missing'))

perf <- perf %>%
  mutate(performance = case_when(
                                nse < 0.5 & abs(pbias) >= 25 ~ 'Neither',
                                nse > 0.5 & abs(pbias) >= 25 ~ 'NSE',
                                nse < 0.5 & abs(pbias) < 25 ~ '% bias satisfactory',
                                nse > 0.5 & abs(pbias) < 25 ~ 'NSE + % bias satisfactory')) %>%
  mutate(input_data = if_else(source == 'grid',
                              'Gridded', 'Station'),
         year_missing = if_else(year_missing == 'None',
                                'all', year_missing))

param_sens <- left_join(param_sens,
                        perf,
                        by = c('input_data',
                               'year_missing'))

param_sens$param <- fct_recode(param_sens$param,
  "snow_trs"        = "snow_trs",
  "baseTemp (°C)"      = "baseTemp",
  "t_factor"    = "t_factor",
  "a_rain (mm)"      = "a_rain",
  "a_snow (mm)"      = "a_snow",
  "lagSurfaceRunoff"    = "lagSurfaceRunoff",
  "soilLatVertLPS"      = "soilLatVertLPS",
  "soilOutLPS"       = "soilOutLPS",
  "lagInterflow"         = "lagInterflow"
)

param_sens$param <- fct_relevel(param_sens$param, 
                                "snow_trs",
                                "baseTemp (°C)",
                                "t_factor",
                                "a_rain (mm)",
                                "a_snow (mm)",
                                "lagSurfaceRunoff",
                                "soilLatVertLPS",
                                "soilOutLPS",
                                "lagInterflow")

# boxplots of top 9
ggplot(param_sens, aes(x=input_data, y=value, fill=input_data)) +
  geom_boxplot(alpha=0.8,
                outlier.shape=NA) +
  facet_wrap(~param, scales = 'free_y',
             strip.position = 'left') +
  labs(y=element_blank(),
       x=element_blank()) +
  theme_bw(base_size=20) +
  stat_compare_means(aes(group = input_data),
                     method = "wilcox.test", 
                     label = "p.signif",
                     hide.ns = T,
                     paired = F,
                     #label.y = 0,
                     #label.x = 1.4,
                     size = 7) +
  geom_jitter(aes(shape = performance),
            position = position_jitter(width = 0.1), 
            size = 2.5, 
            alpha = 0.6,
            stroke = 1,
            color = "black") +
  scale_shape_manual(values = c(
  "% bias satisfactory" = 1,
  "NSE + % bias satisfactory" = 16
)) +
  scale_fill_manual(values = c("#0047AB", "orange"),
                    guide='none') +
    theme(
    legend.position = 'bottom',
    #legend.justification = c(0, 1.1), 
    legend.text = element_text(size = 16),
    legend.title = element_blank(), 
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.placement = 'outside',
    #strip.background = element_blank(),
    axis.title.y = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.25)))

ggsave('./figures/figure5_oct2025.png',
       dpi=600,
       width=12,
       height=8,
       bg='white')

## same as above but with param limits added
param_limits <- data.frame(
  param = c("snow_trs", "baseTemp (°C)", "t_factor",
            "a_rain (mm)", "a_snow (mm)", "lagSurfaceRunoff",
            "soilLatVertLPS", "soilOutLPS", "lagInterflow"),
  low  = c(-5, -5, 0, 0.1, 0.1, 1, 0.001, 0.01, 1),
  high = c(5, 5, 5, 10, 10, 1.5, 10, 10, 2)
)


param_lines <- param_limits %>%
  pivot_longer(cols = c(low, high),
               names_to = "type", 
               values_to = "y")

# Make sure param in param_lines is a factor with the same order
param_lines$param <- fct_relevel(param_lines$param,
                                 "snow_trs",
                                 "baseTemp (°C)",
                                 "t_factor",
                                 "a_rain (mm)",
                                 "a_snow (mm)",
                                 "lagSurfaceRunoff",
                                 "soilLatVertLPS",
                                 "soilOutLPS",
                                 "lagInterflow")

ggplot(param_sens, aes(x=input_data, y=value, fill=input_data)) +
  # add horizontal lines for low/high values
  geom_hline(data = param_lines, aes(yintercept = y),
             linetype = "dashed", color = "grey70") +
  geom_boxplot(alpha=0.8,
                outlier.shape=NA) +
  facet_wrap(~param, scales = 'free_y',
             strip.position = 'left') +
  labs(y=element_blank(),
       x=element_blank()) +
  theme_bw(base_size=20) +
  stat_compare_means(aes(group = input_data),
                     method = "wilcox.test", 
                     label = "p.signif",
                     hide.ns = T,
                     paired = F,
                     #label.y = 0,
                     #label.x = 1.4,
                     size = 7) +
  geom_jitter(aes(shape = performance),
            position = position_jitter(width = 0.1), 
            size = 2.5, 
            alpha = 0.6,
            stroke = 1,
            color = "black") +
  scale_shape_manual(values = c(
  "% bias satisfactory" = 1,
  "NSE + % bias satisfactory" = 16
)) +
  scale_fill_manual(values = c("#0047AB", "orange"),
                    guide='none') +
    theme(
    legend.position = 'bottom',
    #legend.justification = c(0, 1.1), 
    legend.text = element_text(size = 16),
    legend.title = element_blank(), 
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.placement = 'outside',
    #strip.background = element_blank(),
    axis.title.y = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.25)))

ggsave('./figures/figure5_wlimits_oct2025.png',
       dpi=600,
       width=12,
       height=8,
       bg='white')

```

### For Supp

```{r}

# show rest of params for supplemental
# first take area weighted params (except lagSurfaceRunoff, a_rain, a_snow since that is already shown in main fig)
otherParamsWeighted <- read_csv('./38HRU_oct2025_updates/updated_wranges/params_weighted_oct2025_ranges.csv') %>%
  filter(!param %in% c('lagSurfaceRunoff',
                       'a_rain',
                       'a_snow')) %>%
  rename(value = area_weighted_average,
         input_data = source) %>%
  dplyr::select(param, input_data, value)
  
# params that were not affected by burn
otherParams <- read_csv('./38HRU_oct2025_updates/updated_wranges/params_unburn_ranges.csv') %>%
  filter(!param %in% c('soilOutLPS',
                       'snow_trs',
                       'lagInterflow',
                       'baseTemp',
                       't_factor',
                       'lagSurfaceRunoff',
                       'a_rain',
                       'a_snow',
                       'soilLatVertLPS')) %>% # these are the ones already shown
  filter(!param %in% otherParamsWeighted$param) %>% # there are the ones that need to be area weighted
  dplyr::select(param, input_data, value, min, max)

# now join the area weighted other to the other params
otherParams <- bind_rows(otherParams, otherParamsWeighted)

# Create a summary dataframe for hlines
lines_df <- otherParams %>%
  dplyr::group_by(param) %>%
  dplyr::summarize(min_val = min(value, na.rm = TRUE),
                   max_val = max(value, na.rm = TRUE))

# supp info plot
ggplot(otherParams, aes(x = input_data, y = value, fill = input_data)) +
  geom_hline(data = lines_df, aes(yintercept = min_val), 
             linetype = "dashed", color = "grey70") +
  geom_hline(data = lines_df, aes(yintercept = max_val), 
             linetype = "dashed", color = "grey70") +
  geom_boxplot(alpha=0.8,
                outlier.colour = "black") +
  facet_wrap(~param, scales = 'free_y',
             ncol=3) +
  labs(y=element_blank(),
       x=element_blank()) +
  theme_bw(base_size=20) +
  stat_compare_means(aes(group = input_data),
                     method = "wilcox.test", 
                     label = "p.signif",
                     hide.ns = T,
                     paired = F,
                     #label.y = 0,
                     #label.x = 1.4,
                     size = 7) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
    theme(
    legend.position = 'none',
    #legend.justification = c(0, 1.1), 
    legend.text = element_text(size = 16),
    legend.title = element_blank(), 
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    #strip.text = element_blank()
  ) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.2))) 

ggsave('./figures/remainingparams_boxplots_SUPP_oct2025.png',
       dpi=600,
       height=16,
       width=10)

```

# Figure 6

```{r}

gw_gridall <- read_csv(here('38HRU_oct2025_updates/catchment_output/grid_all.csv'), skip = 3) %>%
  slice(-c(1,2)) %>%
  dplyr::select(time,
                catchmentRD1_w, 
                catchmentRD2_w, 
                catchmentRG1_w, 
                catchmentRG2_w) %>%
  mutate(source = 'grid_all') %>%
  mutate(across(c(catchmentRD1_w, 
                  catchmentRD2_w, 
                  catchmentRG1_w, 
                  catchmentRG2_w), 
                as.numeric))

gw_statnall <- read_csv(here('38HRU_oct2025_updates/catchment_output/statn_all.csv'), skip = 3) %>%
  slice(-c(1,2)) %>%
  dplyr::select(time, 
                catchmentRD1_w, 
                catchmentRD2_w, 
                catchmentRG1_w, 
                catchmentRG2_w) %>%
  mutate(source = 'statn_all') %>%
  mutate(across(c(catchmentRD1_w, 
                  catchmentRD2_w, 
                  catchmentRG1_w, 
                  catchmentRG2_w), 
                as.numeric))

# combine the two above
gw <- bind_rows(
  gw_gridall, gw_statnall) %>%
  mutate(date = ymd(time),
         year = year(date)) %>%
  arrange(date) %>%
  group_by(year, source) %>%
  mutate(RD1cumsum = cumsum(catchmentRD1_w),
         RD2cumsum = cumsum(catchmentRD2_w),
         RG1cumsum = cumsum(catchmentRG1_w),
         RG2cumsum = cumsum(catchmentRG2_w))

gw_maxcumsum <- gw %>%
  group_by(source, year) %>%
  summarize(yr_cum_RD1 = max(RD1cumsum),
            yr_cum_RD2 = max(RD2cumsum),
            yr_cum_RG1 = max(RG1cumsum),
            yr_cum_RG2 = max(RG2cumsum)) %>%
  mutate(year = as.factor(year)) %>%
  pivot_longer(!c(year, source), names_to = 'flow_type', values_to = 'flow_cms') %>%
  mutate(source = if_else(source == 'grid_all',
                          'Gridded',
                          'Station'))

# make a vector of the letters - this is from the ANOVA+Tukey results in fourmile_output_dec2024
letters_vector <- c("a", "b", "b", "c", "c", "c", "c", "c")

gw_maxcumsum <- gw_maxcumsum %>%
  mutate(letter = case_when(
    source == "Gridded" & flow_type == "yr_cum_RG1" ~ letters_vector[1],
    source == "Station" & flow_type == "yr_cum_RG1" ~ letters_vector[2],
    source == "Station" & flow_type == "yr_cum_RD2" ~ letters_vector[3],
    source == "Gridded" & flow_type == "yr_cum_RD1" ~ letters_vector[4],
    source == "Station" & flow_type == "yr_cum_RD1" ~ letters_vector[5],
    source == "Gridded" & flow_type == "yr_cum_RD2" ~ letters_vector[6],
    source == "Gridded" & flow_type == "yr_cum_RG2" ~ letters_vector[7],
    source == "Station" & flow_type == "yr_cum_RG2" ~ letters_vector[8]
  ))

# now make the same figure as above but with letters
facet_labels <- c('yr_cum_RD1' = 'Surface runoff',
                  'yr_cum_RD2' = 'Interflow',
                  'yr_cum_RG1' = 'Fast groundwater',
                  'yr_cum_RG2' = 'Slow groundwater')

perf <- read_csv('./38HRU_oct2025_updates/nse_pbias_grid_statn_all.csv') %>%
  mutate(year = as.factor(year))

gw_maxcumsum <- left_join(gw_maxcumsum,
                          perf,
                          by = c('source',
                                 'year'))

gw_maxcumsum <- gw_maxcumsum %>%
  mutate(flow_cms = if_else(flow_type == 'yr_cum_RD1' &
                                flow_cms > 25,
                              NA,
                              flow_cms))

gw_maxcumsum_letters <- gw_maxcumsum %>%
  group_by(source, flow_type) %>%
  mutate(max = max(flow_cms)) %>%
  distinct(flow_type, source, .keep_all = TRUE) %>%
    mutate(max = if_else((flow_type == 'yr_cum_RD1' & 
                           source == 'Gridded'),
                         3.5, max)) %>%
    mutate(max = if_else((flow_type == 'yr_cum_RD1' & 
                           source == 'Station'),
                         1.3, max)) %>%
  mutate(y_text = max * 1.06)

flow_box <- ggplot(gw_maxcumsum, aes(x = source, y = flow_cms, fill = source)) +
  geom_boxplot(outliers=F,width=0.7) + # need to note 1 outlier is removed from RD1 grid and statn (2013 flood) ****
  geom_jitter(
    aes(shape = both),
    position = position_jitter(width = 0.25),
    size = 2.5,
    alpha = 0.7,
    stroke = 1,
    color = "black") +
  scale_shape_manual(values = c(
  "NSE + % bias unsatisfactory" = 4,
  "NSE + % bias satisfactory" = 16,
  "NSE satisfactory" = 1)) +
  geom_text(data = gw_maxcumsum_letters, 
            aes(label=letter,
                y=y_text),
            position = position_dodge(width = 0.97),
            size = 6, 
            vjust = 0) + 
  facet_wrap(~flow_type, 
             scales = 'free',
             labeller = labeller(flow_type = facet_labels)) +
  labs(y = 'mm of water') + 
  theme_bw(base_size=20) +
  scale_fill_manual(values = c("#0047AB", "orange"), guide = 'none') +
  theme(
    #legend.position = c(0.94, 0.36),
    legend.position = 'bottom',
    legend.text = element_text(size = 16),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    axis.title.x = element_blank(),
    legend.spacing = unit(0.1, "lines"),
    legend.margin = margin(t = -8, r = 0, b = -2, l = 0)) +
    #axis.text.x = element_blank(),
    #axis.ticks.x = element_blank()) +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.2))) 

flow_box

ggsave('./figures/figure6_oct2025.png',
       dpi=600,
       width = 12,
       height = 8)

# get some stats for manuscript
stats <- gw %>%
  group_by(source, year) %>%
  summarize(yr_cum_RD1 = max(RD1cumsum),
            yr_cum_RD2 = max(RD2cumsum),
            yr_cum_RG1 = max(RG1cumsum),
            yr_cum_RG2 = max(RG2cumsum)) %>%
  mutate(year = as.factor(year)) %>%
  pivot_longer(!c(year, source), names_to = 'flow_type', values_to = 'flow_cms') %>%
  mutate(source = if_else(source == 'grid_all',
                          'Gridded',
                          'Station')) %>% 
  group_by(source, year) %>%
  mutate(totFlow = sum(flow_cms)) %>%
  group_by(source, year) %>%
  mutate(fracFlow = (flow_cms/totFlow)*100) %>%
  group_by(source, flow_type) %>% 
  summarize(meanPercFlow = mean(fracFlow))

```

# Figure 7

HRU low and high for 2016
HRU high = 18
HRU low = 19

```{r}

statn_hi <- read_csv('./38HRU_oct2025_updates/HRU/statn_HRU_18.csv') %>% 
  mutate(date = mdy(time),
         source = 'statn') %>%
  dplyr::select(-time)

grid_hi <- read_csv('./38HRU_oct2025_updates/HRU/grid_HRU_18.csv') %>%
  mutate(date = mdy(time),
         source = 'grid') %>%
  dplyr::select(-time)

both_hi <- bind_rows(statn_hi, grid_hi) %>%
  mutate(year = year(date),
         month = month(date)) %>%
  filter(year == 2016,
         month %in% c(4,5,6))

statn_low <- read_csv('./38HRU_oct2025_updates/HRU/statn_HRU_19.csv') %>% 
  mutate(date = mdy(time),
         source = 'statn') %>%
  dplyr::select(-time)

grid_low <- read_csv('./38HRU_oct2025_updates/HRU/grid_HRU_19.csv') %>%
  mutate(date = mdy(time),
         source = 'grid') %>%
  dplyr::select(-time)

both_low <- bind_rows(statn_low, grid_low) %>%
  mutate(year = year(date),
         month = month(date)) %>%
  filter(year == 2016,
         month %in% c(4,5,6))

## combine low and high together
hi <- both_hi %>%
  dplyr::select(tmean, snowTotSWE, precip, source, date) %>%
  mutate(elevation = 'High')

low <- both_low %>%
  dplyr::select(tmean, snowTotSWE, precip, source, date) %>%
  mutate(elevation = 'Low')

both <- bind_rows(hi, low) %>%
  mutate(elev_source =
           case_when(source == 'statn' & elevation == 'High' ~ 'Station - High',
                     source == 'statn' & elevation == 'Low' ~ 'Station - Low',
                     source == 'grid' & elevation == 'High' ~ 'Gridded - High',
                     source == 'grid' & elevation == 'Low' ~ 'Gridded - Low'))

# figure
tmean <- ggplot(both,
       aes(x=date, y = tmean, 
           color = elev_source,
           linetype=elev_source)) +
   geom_line(size=1, alpha=0.8) +  
    scale_color_manual(values = c("Gridded - High" = "#0047AB", 
                                  "Gridded - Low" = "#0047AB", 
                                  "Station - High" = "orange",
                                  "Station - Low" = "orange")) +
  scale_linetype_manual(values = c("Gridded - High" = "dashed", 
                                  "Gridded - Low" = "solid", 
                                  "Station - High" = "dashed",
                                  "Station - Low" = "solid")) + 
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'Mean temperature (°C)') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
    #plot.margin = margin(t = 10, r = 20, b = 10, l = 10)
  ) 

tmean

swe <- ggplot(both,
       aes(x=date, y = snowTotSWE, 
           color = elev_source,
           linetype=elev_source)) +
   geom_line(size=1, alpha=0.8) +  
    scale_color_manual(values = c("Gridded - High" = "#0047AB", 
                                  "Gridded - Low" = "#0047AB", 
                                  "Station - High" = "orange",
                                  "Station - Low" = "orange")) +
  scale_linetype_manual(values = c("Gridded - High" = "dashed", 
                                  "Gridded - Low" = "solid", 
                                  "Station - High" = "dashed",
                                  "Station - Low" = "solid")) + 
  scale_x_date(date_labels = "%b") +
  #scale_y_log10() +
  labs(x = element_blank(),
       y = 'SWE (mm)') +
  theme_bw(base_size = 20) +
  theme(
    #legend.position = c(0.89, 0.87),
    legend.position = 'bottom',
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
    #plot.margin = margin(t = 10, r = 20, b = 10, l = 10)
  ) 

swe

p <- both %>%
  group_by(elev_source) %>%
  mutate(cumP = cumsum(precip)) %>% 
  ggplot(.,
       aes(x=date, y = cumP, 
           color = elev_source,
           linetype=elev_source)) +
   geom_line(size=1, alpha=0.8) +  
    scale_color_manual(values = c("Gridded - High" = "#0047AB", 
                                  "Gridded - Low" = "#0047AB", 
                                  "Station - High" = "orange",
                                  "Station - Low" = "orange")) +
  scale_linetype_manual(values = c("Gridded - High" = "dashed", 
                                  "Gridded - Low" = "solid", 
                                  "Station - High" = "dashed",
                                  "Station - Low" = "solid")) + 
  scale_x_date(date_labels = "%b") +
  #scale_y_log10() +
  labs(x = element_blank(),
       y = 'Precip (mm)') +
  theme_bw(base_size = 20) +
  theme(
    legend.position = 'bottom',
    #legend.text = element_text(size = 12),
    #legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
    #plot.margin = margin(t = 10, r = 20, b = 10, l = 10)
  ) 

p

legend <- cowplot::get_plot_component(tmean, "guide-box", return_all = TRUE)[[3]]

tmean_noleg <- tmean + theme(legend.position = "none")
p_noleg <- p + theme(legend.position = "none")
swe_noleg <- swe + theme(legend.position = "none")

combined <- plot_grid(tmean_noleg, p_noleg, swe_noleg, nrow = 1)
final_plot <- plot_grid(combined, legend, ncol = 1, rel_heights = c(1, 0.1))
final_plot

ggsave('./figures/figure7_oct2025.png',
       width = 10,
       height = 5,
       dpi=800,
       bg='white')


```

# Figure 8

```{r}

flow <- read_csv('./38HRU_oct2025_updates/discharge_all.csv') %>%
  replace(.==-9999, NA) %>%
  rename(date = time) %>%
  mutate(date = mdy(date)) %>%
  drop_na()

flow_pivot <- flow %>%
  pivot_longer(!date, names_to = 'cal_run', values_to = 'q_m3s') %>%
  mutate(year = as.factor(year(date))) %>%
  filter(cal_run %in% c('grid_all',
                        'statn_all',
                        'obs'
                        #'statn_2016',
                        #'grid_2016'
                        )) %>%
  mutate(cal_run = case_match(cal_run,
                            'grid_all' ~ 'Gridded',
                            'statn_all' ~ 'Station',
                            'obs' ~ 'Observed'
                          # 'statn_2016' ~ 'statn_2016',
                          #  'grid_2016' ~ 'grid_2016'
  ))

# 2016 hydrograph
flowEg <- flow_pivot %>%
  filter(year %in% c(2016)) %>%
  ggplot(aes(x = date,
             y = q_m3s, 
             color = cal_run,
             linetype = cal_run)) + 
  geom_line(size = 1, alpha = 1) + 
  theme_bw(base_size = 20) +
  scale_color_manual(values = c("Gridded" = "#0047AB", 
                                "Observed" = "black", 
                                "Station" = "orange"
                               # 'statn_2016' = 'orange',
                              #  'grid_2016' = '#0047AB'
                                )) +
  scale_linetype_manual(values = c("Gridded" = "solid",
                                   "Observed" = "dashed", 
                                   "Station" = "solid"
                                   #'statn_2016' = 'twodash',
                               #'grid_2016' = 'twodash'
)) +
  labs(x = element_blank(),
       y = "Streamflow (cms)") +
   scale_x_date(date_labels = "%b",
               date_breaks = "1 month") +
  theme(
    legend.position = c(0.9, 0.85),
    legend.text = element_text(size = 14),
    legend.key.width = unit(2, "lines"),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 2, r = 20, b = 2, l = 10)
  )

flowEg

# 2016 flow partition
gw_gridall <- read_csv(here('38HRU_oct2025_updates/catchment_output/grid_all.csv'), skip = 3) %>%
  slice(-c(1,2)) %>%
  dplyr::select(time,
                catchmentRD1_w, 
                catchmentRD2_w, 
                catchmentRG1_w, 
                catchmentRG2_w) %>%
  mutate(source = 'grid_all') %>%
  mutate(across(c(catchmentRD1_w, 
                  catchmentRD2_w, 
                  catchmentRG1_w, 
                  catchmentRG2_w), 
                as.numeric))

gw_statnall <- read_csv(here('38HRU_oct2025_updates/catchment_output/statn_all.csv'), skip = 3) %>%
  slice(-c(1,2)) %>%
  dplyr::select(time, 
                catchmentRD1_w, 
                catchmentRD2_w, 
                catchmentRG1_w, 
                catchmentRG2_w) %>%
  mutate(source = 'statn_all') %>%
  mutate(across(c(catchmentRD1_w, 
                  catchmentRD2_w, 
                  catchmentRG1_w, 
                  catchmentRG2_w), 
                as.numeric))

# combine the two above
gw <- bind_rows(
  gw_gridall, gw_statnall) %>%
  mutate(date = ymd(time),
         year = year(date)) %>%
  arrange(date) %>%
  group_by(year, source) %>%
  mutate(RD1cumsum = cumsum(catchmentRD1_w),
         RD2cumsum = cumsum(catchmentRD2_w),
         RG1cumsum = cumsum(catchmentRG1_w),
         RG2cumsum = cumsum(catchmentRG2_w))

example <- gw %>%
  filter(year == 2016) %>%
  ungroup() %>% 
  dplyr::select(date, source,
         RD1cumsum,
         RD2cumsum,
         RG1cumsum,
         RG2cumsum) %>%
  pivot_longer(!c(date,source), names_to='flow_type',
               values_to='flow_cms') %>%
  mutate(source = if_else(source == 'grid_all',
                          'Gridded',
                          'Station'))

# some 2016 stats
flow16Stats <- example %>%
  filter(date == '2016-12-31') %>%
  group_by(source) %>%
  mutate(sum = sum(flow_cms)) %>%
  mutate(percTot = (flow_cms/sum)*100) %>%
  mutate(percTot = round(percTot, 2))

facet_labels <- c('RD1cumsum' = 'Surface runoff',
                  'RD2cumsum' = 'Interflow',
                  'RG1cumsum' = 'Fast groundwater',
                  'RG2cumsum' = 'Slow groundwater')

example_yr <- ggplot(example,
       aes(x=date, y = flow_cms, color=source)) +
  geom_line() +
  facet_wrap(~flow_type, 
             scales = 'free_y',
             labeller = labeller(flow_type = facet_labels)) +
   geom_line(size=1, alpha=0.7) +  
  scale_color_manual(values = c("#0047AB", "orange")) +
    scale_x_date(date_labels = "%b", 
               date_breaks = "2 month") +
  labs(x=element_blank(),
       y='mm of water') +
  theme_bw(base_size = 16) +
  theme(
    legend.position = 'none',
    legend.text = element_text(size = 12),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    plot.margin = margin(t = 2, r = 20, b = 10, l = 10)
  )

example_yr

plot_grid(flowEg,
          example_yr,
          ncol=1)

ggsave('./figures/figure8_oct2025.png',
       dpi=800,
       width=10,
       height=8)


```

# Figure 9

```{r}

# params that were cal w/ burned areas
combo <- read_csv('./38HRU_oct2025_updates/params_burn_unburn.csv')

# read in pbias and nse cats
pbias <- read_csv('./38HRU_oct2025_updates/pbiasCats.csv') %>%
  filter(year == c('All')) %>%
  dplyr::select(source, year_missing, pbias)

nse <- read_csv('./38HRU_oct2025_updates/nseCats.csv') %>%
  filter(year == c('All')) %>%
  dplyr::select(source, year_missing, nse)

perf <- left_join(nse, pbias, by = c('source',
                                     'year_missing'))

# assign categories
perf <- perf %>%
  mutate(performance = case_when(
                                nse < 0.5 & abs(pbias) >= 25 ~ 'Neither',
                                nse > 0.5 & abs(pbias) >= 25 ~ 'NSE',
                                nse < 0.5 & abs(pbias) < 25 ~ '% bias satisfactory',
                                nse > 0.5 & abs(pbias) < 25 ~ 'NSE + % bias satisfactory')) %>%
  mutate(input_data = if_else(source == 'grid',
                              'Gridded', 'Station'),
         year_missing = if_else(year_missing == 'None',
                                'all', year_missing))
perf1 <- perf %>%
  mutate(year_missing = if_else(year_missing == 'all',
                                'none',
                                year_missing))

combo <- left_join(combo,
                        perf1,
                        by = c('input_data',
                               'year_missing'))

# reorder the params
# combo$param <- factor(combo$param, levels = c("a_snow",
#                                                         "a_rain",
#                                                         "soilMaxInfSummer",
#                                                         "soilMaxDPS",
#                                                         "lagSurfaceRunoff",
#                                                         "soilDistMPSLPS"))
combo <- combo %>%
  mutate(param = fct_recode(param,
    "a_rain (mm)" = "a_rain",
    "a_snow (mm)" = "a_snow",
    "soilMaxInfSummer (mm/day)" = "soilMaxInfSummer",
    "soilMaxDPS (mm)" = "soilMaxDPS",
    "lagSurfaceRunoff" = "lagSurfaceRunoff",
    "soilDistMPSLPS" = "soilDistMPSLPS"
  ))

# text above boxplots - this is from Tukey analysis that was already run below then added to params
combo <- combo %>%
  group_by(param, burn, input_data) %>%
  mutate(y_text = max(value, na.rm = TRUE) * 1.08) %>%  # Slightly above max value
  ungroup()

ggplot(combo, aes(x = burn, y = value, fill = input_data)) +
  geom_boxplot(alpha = 0.8, 
               outliers = F) +
  geom_text(aes(label = letter, y = y_text), 
            position = position_dodge(width = 0.75),  # Align with boxplots
            size = 6, 
            vjust = 0) +  
  geom_jitter(aes(shape = performance),
            position = position_jitterdodge(
    jitter.width = 0.1,
    dodge.width = 0.75),
            size = 2.5, 
            alpha = 0.6,
            stroke = 1,
            color = "black") +
  scale_shape_manual(values = c(
  "% bias satisfactory" = 1,
  "NSE + % bias satisfactory" = 16)) +
  facet_wrap(~param, 
             scales = 'free_y',
             strip.position = 'left') +
  labs(y = element_blank(), x = element_blank()) +
  theme_bw(base_size = 20) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
  theme(
    legend.position = 'bottom',
    legend.text = element_text(size = 16),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    strip.placement = 'outside',
    axis.title.y = element_blank()
  ) +
   scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))

ggsave('./figures/figure9_oct2025.png',
       dpi=800,
       width = 12,
       height = 8)


```

# Figure 10

```{r}


unburn <- read_csv('./38HRU_oct2025_updates/HRU/statn_HRU_2_unburn.csv') %>%
  mutate(date = mdy(time),
         year = year(date),
         type = 'unburn') %>%
  filter(year == 2016)

burn <- read_csv('./38HRU_oct2025_updates/HRU/statn_HRU_5_burn.csv') %>%
  mutate(date = mdy(time),
         year = year(date),
         type = 'burn') %>%
  filter(year == 2016)

both <- bind_rows(unburn, burn)

# interception
inter <- both %>%
  dplyr::select(date, type, intercStorage)

# swe
swe <- both %>%
  dplyr::select(date, type, snowTotSWE)

p <- both %>%
  dplyr::select(date, type, precip) %>%
  group_by(type) %>%
  mutate(p_cumu = cumsum(precip))

# soil sat
soilsat <- both %>%
  dplyr::select(date, type, soilSat)

et <- both %>%
  dplyr::select(date, type, actET)

# surface runoff
runoff <- both %>%
  dplyr::select(date, type, outRD1)

# interflow
interflow <- both %>%
  dplyr::select(date, type, outRD2) %>%
  mutate(interflow_cum = cumsum(outRD2))

gw <- both %>%
  dplyr::select(date, type, outRG1) %>%
  mutate(gw_cumu = cumsum(outRG1))

# dps
dps <- both %>%
  dplyr::select(date, type, actDPS)

# mps
mps <- both %>%
  dplyr::select(date, type, soilSatMPS)

# lps
lps <- both %>%
  dplyr::select(date, type, soilSatLPS)

# soil sat
soilsat <- both %>%
  dplyr::select(date, type, soilSat)

## make the actual plot
p_plot <- ggplot(p, aes(x = date,
                        y = p_cumu, 
                        color = type)) +
  geom_line(size=1, alpha=0.8) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'Precipitation (mm)') +
  theme_bw(base_size = 18) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 12),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

p_plot

inter <- inter %>%
  mutate(type = factor(type, levels = c("unburn", "burn")))

int_plot <- ggplot(inter, aes(x = date,
                        y = intercStorage, 
                        color = type)) +
  geom_line(size=1, alpha=0.7) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'Interception (mm)') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

int_plot

soilsat_plot <- ggplot(soilsat, aes(x = date,
                        y = soilSat, 
                        color = type)) +
  geom_line(size=1, alpha=0.7) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'Soil saturation') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

soilsat_plot

et_plot <- ggplot(et, aes(x = date,
                        y = actET, 
                        color = type)) +
  geom_line(size=1, alpha=0.7) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'ET (mm)') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

et_plot


interflow_plot <- ggplot(interflow, aes(x = date,
                        y = interflow_cum, 
                        color = type)) +
  geom_line(size=1, alpha=0.7) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'Interflow (L)') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

interflow_plot

gw_plot <- ggplot(gw, aes(x = date,
                        y = gw_cumu, 
                        color = type)) +
  geom_line(size=1, alpha=0.7) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'Shallow groundwater (L)') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

gw_plot

swe_plot <- ggplot(swe, aes(x = date,
                        y = snowTotSWE, 
                        color = type)) +
  geom_line(size=1, alpha=0.7) +
    scale_color_manual(values = c("burn" = "red", 
                                  "unburn" = "black")) +
  scale_x_date(date_labels = "%b") +
  labs(x = element_blank(),
       y = 'SWE (mm)') +
  theme_bw(base_size = 20) +
  theme(legend.position = 'bottom',
    #legend.position = c(0.24, 0.852), 
    legend.text = element_text(size = 10),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    legend.key.width = unit(1, "cm")
  ) 

swe_plot

legend <- cowplot::get_plot_component(p_plot, "guide-box", return_all = TRUE)[[3]]

p_plot <- p_plot + theme(legend.position = "none")
int_plot <- int_plot + theme(legend.position = "none")
soilsat_plot <- soilsat_plot + theme(legend.position = "none")
interflow_plot <- interflow_plot + theme(legend.position = "none")
gw_plot <- gw_plot + theme(legend.position = "none")
swe_plot <- swe_plot + theme(legend.position = "none")
et_plot <- et_plot + theme(legend.position = "none")


plots <- plot_grid( #p_plot,
          int_plot,
          swe_plot,
          soilsat_plot,
          et_plot,
          interflow_plot,
          gw_plot,
          ncol = 3)

final_plot <- plot_grid(
  plots,
  legend,
  ncol = 1,
  rel_heights = c(1, 0.07)  # Adjust height of legend
)

final_plot

ggsave('./figures/figure10_oct2025.png',
       dpi=800,
       bg='white',
       height=8,
       width=12)


```

# Figure 11

```{r}

perf <- read_csv('/Users/megansears/Documents/Repos/fourmile/38HRU_oct2025_updates/perf_metrics.csv')

perf <- perf %>%
  pivot_wider(names_from=metric,
               values_from=value) %>%
  filter(year == 'All')

perf1 <- perf %>%
  mutate(type = case_when(
    str_detect(model_run, "grid") ~ "Gridded",
    str_detect(model_run, "statn") ~ "Station"))

nse_kge <- ggplot(perf1, aes(x=KGE, y=NSE, color=type)) + 
  #geom_point(size=4, alpha=0.7) +
   geom_jitter(size = 4, alpha = 0.7, width = 0.05, height = 0.05) +
  theme_bw(base_size=20) +
  scale_color_manual(values = c("#0047AB", "orange")) +
  theme(
    legend.position = 'bottom',
    legend.text = element_text(size = 16),
    legend.title = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    panel.grid.major.x = element_blank()  # remove vertical major grid lines
   # panel.grid.minor.x = element_blank(),
    #panel.grid.minor = element_blank()      # remove all minor grid lines
    
  )

nse_kge


pbias_kge <- ggplot(perf1, aes(x=KGE, y=Bias, color=type)) + 
  #geom_point(size=4, alpha=0.8) +
  geom_jitter(size = 4, alpha = 0.7, width = 0.001, height = 0.001) +
  theme_bw(base_size=20) +
  scale_color_manual(values = c("#0047AB", "orange")) +
  labs(y = 'Bias') +
  theme(
    legend.position = 'bottom',
    legend.text = element_text(size = 16),
    legend.title = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    panel.grid.major.x = element_blank()  # remove vertical major grid lines
   # panel.grid.minor.x = element_blank(),
    #panel.grid.minor = element_blank()      # remove all minor grid lines
    
  )

pbias_kge

library(patchwork)

combined_plot <- nse_kge + pbias_kge + 
  plot_layout(ncol = 2, guides = "collect") & 
  theme(legend.position = 'bottom')

combined_plot

ggsave('/Users/megansears/Documents/Repos/fourmile/figures/figure11_oct2025.png',
       dpi=600,
       width=10,
       height=6)

```

