---
title: "Fourmile Calibrations and Output"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(plotly)
library(ggpubr)
library(broom)
library(multcompView)

```

# Sensitivity analysis

```{r}
statn <- read_csv('./data/sens_analysis/output_rsa_kge_runoff_statn.csv') %>%
  rename(statn_sens = sensitivity)

grid <- read_csv('./data/sens_analysis/output_rsa_kge_runoff_grid.csv') %>%
  rename(grid_sens = sensitivity)

join <- left_join(statn, grid, by ='parameter')

# rank them
join <- join %>%
  mutate(grid_rank = rank(-grid_sens),
         statn_rank = rank(-statn_sens),
         avg_rank = (grid_rank + statn_rank)/2) %>%
  arrange(avg_rank)

# in the average top 10 rank:
# soilOutLPS, snow_trs, lagSurfaceRunoff, a_rain, lagInterflow,
# baseTemp, a_snow, t_factor, soilLatVertLPS, r_factor
# all but the last two are in statn and grids top 10,
# so show the first 8 in the plot
# rest of params show in the supp

```

# Parameters selected from above

```{r}
# params area weighted (only for lagSurfaceRunoff, a_rain, a_snow)
params <- read_csv('./38HRU_dec2024_updates/params_weighted_dec2024.csv') %>%
  filter(param %in% c('lagSurfaceRunoff',
                      'a_rain',
                      'a_snow')) %>% # select params in the top 8 sens that are area weighted
  rename(value = area_weighted_average,
         input_data = source) %>%
  dplyr::select(param, input_data, value)

# params unburned (above is params that needed to be area weighted bc burn/unburn)
params_unburn <- read_csv('./38HRU_dec2024_updates/params_unburn.csv') %>%
  filter(param %in% c('soilOutLPS',
                      'snow_trs',
                      'lagInterflow',
                      'baseTemp',
                      't_factor',
                      'soilLatVertLPS')) %>%
  dplyr::select(param, input_data, value)

# join the two to get the top 8 sensitve params
param_sens <- bind_rows(params, params_unburn) %>% 
  mutate(input_data = if_else(input_data == 'grid',
                              'Gridded',
                              'Station'))

# get distribution for signf. test
ggplot(param_sens, aes(x = value, fill = input_data)) +
  geom_density(alpha = 0.6) +
  facet_wrap(~param, scales = "free") +
  theme_bw(base_size = 20) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
  theme(
    strip.background = element_blank(),
    panel.grid = element_blank(),
    legend.position = "bottom"
  )

# boxplots of top 8
ggplot(param_sens, aes(x=input_data, y=value, fill=input_data)) +
  geom_boxplot(alpha=0.8,
                outlier.colour = "black") +
  facet_wrap(~param, scales = 'free_y') +
  labs(y=element_blank(),
       x=element_blank()) +
  theme_bw(base_size=20) +
  stat_compare_means(aes(group = input_data),
                     method = "wilcox.test", 
                     label = "p.signif",
                     hide.ns = T,
                     paired = F,
                     #label.y = 0,
                     #label.x = 1.4,
                     size = 7) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
    theme(
    legend.position = 'none',
    #legend.justification = c(0, 1.1), 
    legend.text = element_text(size = 16),
    legend.title = element_blank(), 
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    #strip.text = element_blank()
  ) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)))

ggsave('./figures/param_sensit_boxplots.png',
       dpi=600)

# show rest of params for supplemental
# first take area weighted params (except lagSurfaceRunoff, a_rain, a_snow since that is already shown in main fig)
otherParamsWeighted <- read_csv('./38HRU_dec2024_updates/params_weighted_dec2024.csv') %>%
  filter(!param %in% c('lagSurfaceRunoff',
                       'a_rain',
                       'a_snow')) %>%
  rename(value = area_weighted_average,
         input_data = source) %>%
  dplyr::select(param, input_data, value)
  
# params that were not affected by burn
otherParams <- read_csv('./38HRU_dec2024_updates/params_unburn.csv') %>%
  filter(!param %in% c('soilOutLPS',
                       'snow_trs',
                       'lagInterflow',
                       'baseTemp',
                       't_factor',
                       'lagSurfaceRunoff',
                       'a_rain',
                       'a_snow',
                       'soilLatVertLPS')) %>% # these are the ones already shown
  filter(!param %in% otherParamsWeighted$param) %>% # there are the ones that need to be area weighted
  dplyr::select(param, input_data, value)

# now join the area weighted other to the other params
otherParams <- bind_rows(otherParams, otherParamsWeighted)

# plot the remaning params for catchment
ggplot(otherParams, aes(x=input_data, y=value, fill=input_data)) +
  geom_boxplot(alpha=0.8,
                outlier.colour = "black") +
  facet_wrap(~param, scales = 'free_y',
             ncol=3) +
  labs(y=element_blank(),
       x=element_blank()) +
  theme_bw(base_size=20) +
  stat_compare_means(aes(group = input_data),
                     method = "wilcox.test", 
                     label = "p.signif",
                     hide.ns = T,
                     paired = F,
                     #label.y = 0,
                     #label.x = 1.4,
                     size = 7) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
    theme(
    legend.position = 'none',
    #legend.justification = c(0, 1.1), 
    legend.text = element_text(size = 16),
    legend.title = element_blank(), 
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    #strip.text = element_blank()
  ) +
  scale_y_continuous(expand = expansion(mult = c(0.001, 0.3)))

ggsave('./figures/remainingparams_boxplots.png',
       dpi=600,
       height=16,
       width=10)


```

# Burn and unburn params

```{r}

combo <- read_csv('./38HRU_dec2024_updates/params_burn_unburn.csv') %>%
  mutate(burn = if_else(burn == "yes", "Burned", "Unburned"),
         input_data = if_else(input_data =='grid', 
                              'Gridded',
                              'Station'))


#write_csv(combo, './38HRU_dec2024_updates/params_burn_unburn.csv')
combo <- read_csv('./38HRU_dec2024_updates/params_burn_unburn.csv')

ggplot(combo, aes(x = value, fill = input_data)) +
  geom_density(alpha = 0.6) +
  facet_wrap(burn ~ param, scales = "free") +
  theme_bw(base_size = 20) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
  theme(
    strip.background = element_blank(),
    panel.grid = element_blank(),
    legend.position = "bottom"
  )


ggplot(combo, aes(x=burn, y=value, fill=input_data)) +
  geom_boxplot(alpha=0.8,
                outlier.colour = "black") +
  geom_text(aes(label = letter)) +
  # stat_compare_means(aes(group = input_data),
  #                    method = "wilcox.test", 
  #                    label = "p.signif",
  #                    hide.ns = T,
  #                    paired = F,
  #                    #label.y = 0,
  #                    #label.x = 1.4,
  #                    size = 7) +
  facet_wrap(~param, scales = 'free_y') +
  labs(y=element_blank(),
       x=element_blank()) +
  theme_bw(base_size=20) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
    theme(
    legend.position = 'bottom',
    #legend.justification = c(0, 1.1), 
    legend.text = element_text(size = 16),
    legend.title = element_blank(), 
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black"),
    #strip.text = element_blank()
  ) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.15)))

ggsave('./figures/burn_unburn_params_tukey.png',
       dpi=600)

# text above boxplots
combo <- combo %>%
  group_by(param, burn, input_data) %>%
  mutate(y_text = max(value, na.rm = TRUE) * 1.08) %>%  # Slightly above max value
  ungroup()

ggplot(combo, aes(x = burn, y = value, fill = input_data)) +
  geom_boxplot(alpha = 0.8, outlier.colour = "black") +
  geom_text(aes(label = letter, y = y_text), 
            position = position_dodge(width = 0.75),  # Align with boxplots
            size = 6, 
            vjust = 0) +  
  facet_wrap(~param, scales = 'free_y') +
  labs(y = element_blank(), x = element_blank()) +
  theme_bw(base_size = 20) +
  scale_fill_manual(values = c("#0047AB", "orange")) +
  theme(
    legend.position = 'bottom',
    legend.text = element_text(size = 16),
    legend.title = element_blank(),
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "white"),
    strip.background = element_blank(),
    text = element_text(color = "black"),
    axis.title = element_text(color = "black"),
    axis.text = element_text(color = "black")
  ) +
   scale_y_continuous(expand = expansion(mult = c(0.05, 0.1)))

ggsave('./figures/burn_unburn_params_tukey.png',
       dpi=600,
       width = 12,
       height = 8)


```

# Anova for Burn/Unburn Params

```{r}

tukey_results <- combo %>%
  rename(burn_status = burn) %>%
  mutate(burn_status = as.factor(burn_status),
         input_data = as.factor(input_data)) %>%
  group_split(param) %>%
  map(function(df) {
    # 2 way anova
    model <- aov(value ~ burn_status * input_data, data = df)
    
    # Tukey HSD
    tukey_test <- TukeyHSD(model)
    
    # Tukey letters based on p val
    tukey_letters <- multcompLetters4(model, tukey_test)

    list(
      parameter = unique(df$param),
      model = model,
      tukey = tukey_test,
      letters = tukey_letters
    )
  })

# Convert results into a tibble
tukey_df <- tibble(
  parameter = map_chr(tukey_results, "parameter"),
  model = map(tukey_results, "model"),
  tukey = map(tukey_results, "tukey"),
  letters = map(tukey_results, "letters")
)

# added tukey letters to parmas_burn_unburn.csv in dec2024 folder



```


