---
title: "Fourmile Calibrations and Output"
author: "Megan Sears"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_float: yes
    theme: journal
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  message = F, 
  warning  = F)

library(tidyverse)
library(plotly)
library(lubridate)
library(knitr)
library(kableExtra)
library(dataRetrieval)
library(hydroGOF)
library(sp)
library(raster)
library(sf)
library(mapview)
library(here)
library(scales)
library(dataRetrieval)
library(tmap)
library(ggpubr)
library(gridExtra)
library(stringr)

```

```{r load in files, include = F}

setwd('/Users/megansears/Documents/Repos/fourmile/38HRU_dec2024_updates')

#kge <- read_csv('calruns_KGE.csv') # skip for now - come back if needed

```


```{r look at kge, echo = F}

# kge_plot <- ggplot(kge, aes(year_missing, KGE, shape = input_data, color = input_data)) + geom_point(size = 3) +
#   theme_bw()
# 
# ggplotly(kge_plot)

```

# Parameters

## Scatter plots

```{r read in params, echo = FALSE, message = FALSE, warning = FALSE, include = F}

setwd("/Users/megansears/Documents/Repos/fourmile/38HRU_dec2024_updates/cals")

#pull in all filenames with composite
filenames <- list.files('.', pattern=".csv", full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 10)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes) #remove dataframes list

```


```{r params, echo = FALSE, message = FALSE, warning = FALSE}

# function to read files, remove top rows, paste site name
read_cals <- function(df, name){
    df <- df %>%
      slice(-c(1:9, 146:277)) %>%
      separate(Parameter, c("Parameter", "value"), sep = ",") %>%
      drop_na() %>%
      dplyr::select(-1) %>% 
      mutate(cal = name)
    

}

# grid_2011 <- read_cals(grid_2011., name = 'grid_2011')
# grid_2012 <- read_cals(grid_2012., name = 'grid_2012')
# grid_2013 <- read_cals(grid_2013., name = 'grid_2013')
# grid_2014 <- read_cals(grid_2014., name = 'grid_2014')
# grid_2015 <- read_cals(grid_2015., name = 'grid_2015')
# grid_2016 <- read_cals(grid_2016., name = 'grid_2016')
# grid_2017 <- read_cals(grid_2017., name = 'grid_2017')
# grid_2018 <- read_cals(grid_2018., name = 'grid_2018')
# grid_2019 <- read_cals(grid_2019., name = 'grid_2019')
# grid_2020 <- read_cals(grid_2020., name = 'grid_2020')
grid_all <- read_cals(grid_all.c, name = 'grid_all')

# grid <- bind_rows(grid_2011, grid_2012, grid_2013, grid_2014, grid_2015,
#                   grid_2016, grid_2017, grid_2018, grid_2019, grid_2020,
#                   grid_all) %>%
#   mutate(input_data = 'grid') %>%
#   mutate(year_missing_almost = gsub('grid_', '', cal)) %>%
#   mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
#   dplyr::select(-c(year_missing_almost)) %>%
#   rename(param = Parameter) %>%
#   filter(!param == 'locGrw',
#          !param == 'tempRes')

grid <- grid_all %>%
  mutate(input_data = 'grid') %>%
  mutate(year_missing_almost = gsub('grid_', '', cal)) %>%
  mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
  dplyr::select(-c(year_missing_almost)) %>%
  rename(param = Parameter) %>%
  filter(!param == 'locGrw',
         !param == 'tempRes')

# statn_2011 <- read_cals(statn_2011, name = 'statn_2011')
# statn_2012 <- read_cals(statn_2012, name = 'statn_2012')
# statn_2013 <- read_cals(statn_2013, name = 'statn_2013')
# statn_2014 <- read_cals(statn_2014, name = 'statn_2014')
# statn_2015 <- read_cals(statn_2015, name = 'statn_2015')
# statn_2016 <- read_cals(statn_2016, name = 'statn_2016')
# statn_2017 <- read_cals(statn_2017, name = 'statn_2017')
# statn_2018 <- read_cals(statn_2018, name = 'statn_2018')
# statn_2019 <- read_cals(statn_2019, name = 'statn_2019')
# statn_2020 <- read_cals(statn_2020, name = 'statn_2020')
statn_all <- read_cals(statn_all., name = 'statn_all')

# statn <- bind_rows(statn_2011, statn_2012, statn_2013, statn_2014, statn_2015,
#                   statn_2016, statn_2017, statn_2018, statn_2019, statn_2020,
#                   statn_all) %>%
#   mutate(input_data = 'statn') %>%
#   mutate(year_missing_almost = gsub('statn_', '', cal)) %>%
#   mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
#   dplyr::select(-c(year_missing_almost)) %>%
#   rename(param = Parameter) %>%
#   filter(!param == 'locGrw',
#          !param == 'tempRes')

statn <- statn_all %>%
  mutate(input_data = 'statn') %>%
  mutate(year_missing_almost = gsub('statn_', '', cal)) %>%
  mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
  dplyr::select(-c(year_missing_almost)) %>%
  rename(param = Parameter) %>%
  filter(!param == 'locGrw',
         !param == 'tempRes')

params <- bind_rows(statn, grid)

params <- params %>%
  filter(!param %in% c('angstrom_a', 'angstrom_b', 
                      'Beta_min', 
                      'Beta_rsd', "Beta_trans", 'clat', 
                      'delayNitrification',
                      'denitrificationRateCoefficient', 
                      'denitrificationSoilSaturationThreshold',
                      'deposition_factor', 'drrad', 
                      'drspac', 'initLPS', 'initRG1',
                      'initRG2', 'Ksink', 'LExCoef', 
                      'longTZ', 'N_concRG1', 'N_concRG2', 'N_delay_RG1',
                      'N_delay_RG2', 
                      'nitrificationSoilTemperatureThreshold', 
                      'nitrificationSurfaceTemperatureThreshold',
                      'opti', 'piadin', 'rootfactor', 'sceno', 
                      'soilImpGT80', 'soilImpLT80',
                      'soilLinRed', 'soilMaxPerc', 'temp_lag')) %>%
    mutate(value = as.numeric(value),
         param = as.factor(param))


#function to plot all params
plot_params <- function(param_name) {
  params %>%
    filter(param == param_name) %>%
    ggplot(aes(x = year_missing,
               y = value,
               shape = input_data, 
               color = input_data)) + 
    geom_point(size = 3) + 
    ggtitle(param_name) +
    theme_bw()
}

name <- levels(params$param)

lapply(name, plot_params)

#write.csv(params, 'params.csv')

# find min and max of grid and statn param for sensitivity analysis
# grid_minmax <- grid %>%
#   group_by(param) %>%
#   summarize(min = as.numeric(min(value)),
#             max = as.numeric(max(value))) %>%
#   mutate(input = 'grid_unburn')
# 
# statn_minmax <- statn %>%
#   group_by(param) %>%
#   summarize(min = as.numeric(min(value)),
#             max = as.numeric(max(value))) %>%
#   mutate(input = 'statn_unburn')
# 
# minmax_burn <- burn_params %>%
#   group_by(params, input_data) %>%
#   summarize(min = min(value),
#             max = max(value)) %>%
#   mutate(input = paste(input_data, '_burn')) %>%
#   dplyr::select(-input_data) %>%
#   rename(param = params) %>%
#   mutate(param = as.character(param))
# 
# minmax_params <- bind_rows(grid_minmax, statn_minmax, minmax_burn)
# write.csv(minmax_params, 'min_max_params.csv')

```



```{r density plots, echo = FALSE, message = FALSE, warning = FALSE}

# mean_params <- params %>%
#   group_by(param, input_data) %>%
#   summarize(mean = mean(value))
# 
# plotdens_params <- function(param_name) {
#   params %>%
#     filter(param == param_name) %>%
#     ggplot(aes(x = value,
#                fill = input_data, 
#                color = input_data)) + 
#     geom_density(alpha=0.5) +
#     geom_vline(data=filter(mean_params, param == param_name), 
#                aes(xintercept=mean, color=input_data),
#              linetype="dashed", linewidth=0.75) +
#     ggtitle(param_name) +
#     theme_bw()
# }
# 
# name <- levels(params$param)
# 
# lapply(name, plotdens_params)

```

## Burn parameters

```{r echo = FALSE, message = FALSE, warning = FALSE, include = F}

# rm(statn_2011, statn_2012, statn_2013, statn_2014, statn_2015,
#                   statn_2016, statn_2017, statn_2018, statn_2019, statn_2020,
#                   statn_all., statn_all)

rm(statn_all)

setwd("/Users/megansears/Documents/Repos/fourmile/38HRU_dec2024_updates/cals")

#pull in all filenames with composite
filenames <- list.files('.', pattern=".csv", full.names=F)

#read all the csvs
dataframes <- lapply(filenames, read_csv)

#name all the csv
names(dataframes) <- substr(filenames, 1, 10)

#extract csvs from list to global env
lapply(names(dataframes), function(x) assign(x, dataframes[[x]], envir = .GlobalEnv))
rm(dataframes) #remove dataframes list

```

```{r echo = FALSE, message = FALSE, warning = FALSE}

# read in all the grid burn params
read_cals_burn <- function(df, name){
    df <- df %>%
      slice(-c(1:274)) %>%
      separate_wider_delim(Parameter, 
                       delim = ',',
                       names = c('soilID',
                                 'luca_a_rain',
                                 'luca_a_snow',
                                 'luca_soilMaxInfSummer',
                                 'luca_soilMaxDPS',
                                 'luca_lagSurfaceRunoff',
                                 'luca_soilDistMPSLPS')) %>%
      slice(-1) %>%
      dplyr::select(-1) %>% 
      mutate(cal = name)
}

# grid_2011_burn <- read_cals_burn(grid_2011., name = 'grid_2011')
# grid_2012_burn <- read_cals_burn(grid_2012., name = 'grid_2012')
# grid_2013_burn <- read_cals_burn(grid_2013., name = 'grid_2013')
# grid_2014_burn <- read_cals_burn(grid_2014., name = 'grid_2014')
# grid_2015_burn <- read_cals_burn(grid_2015., name = 'grid_2015')
# grid_2016_burn <- read_cals_burn(grid_2016., name = 'grid_2016')
# grid_2017_burn <- read_cals_burn(grid_2017., name = 'grid_2017')
# grid_2018_burn <- read_cals_burn(grid_2018., name = 'grid_2018')
# grid_2019_burn <- read_cals_burn(grid_2019., name = 'grid_2019')
# grid_2020_burn <- read_cals_burn(grid_2020., name = 'grid_2020')
grid_all_burn <- read_cals_burn(grid_all.c, name = 'grid_all')

# grid_burn <- bind_rows(grid_2011_burn, 
#                   grid_2012_burn, 
#                   grid_2013_burn, 
#                   grid_2014_burn, 
#                   grid_2015_burn,
#                   grid_2016_burn, 
#                   grid_2017_burn, 
#                   grid_2018_burn, 
#                   grid_2019_burn, 
#                   grid_2020_burn,
#                   grid_all_burn) %>%
#   mutate(input_data = 'grid') %>%
#   mutate(year_missing_almost = gsub('grid_', '', cal)) %>%
#   mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
#   dplyr::select(-c(year_missing_almost))

grid_burn <- grid_all_burn %>%
  mutate(input_data = 'grid') %>%
  mutate(year_missing_almost = gsub('grid_', '', cal)) %>%
  mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
  dplyr::select(-c(year_missing_almost))

# now do statn burn params
# statn_2011_burn <- read_cals_burn(statn_2011, name = 'statn_2011')
# statn_2012_burn <- read_cals_burn(statn_2012, name = 'statn_2012')
# statn_2013_burn <- read_cals_burn(statn_2013, name = 'statn_2013')
# statn_2014_burn <- read_cals_burn(statn_2014, name = 'statn_2014')
# statn_2015_burn <- read_cals_burn(statn_2015, name = 'statn_2015')
# statn_2016_burn <- read_cals_burn(statn_2016, name = 'statn_2016')
# statn_2017_burn <- read_cals_burn(statn_2017, name = 'statn_2017')
# statn_2018_burn <- read_cals_burn(statn_2018, name = 'statn_2018')
# statn_2019_burn <- read_cals_burn(statn_2019, name = 'statn_2019')
# statn_2020_burn <- read_cals_burn(statn_2020, name = 'statn_2020')
statn_all_burn <- read_cals_burn(statn_all., name = 'statn_all')

# statn_burn <- bind_rows(statn_2011_burn, 
#                   statn_2012_burn, 
#                   statn_2013_burn, 
#                   statn_2014_burn, 
#                   statn_2015_burn,
#                   statn_2016_burn, 
#                   statn_2017_burn, 
#                   statn_2018_burn, 
#                   statn_2019_burn, 
#                   statn_2020_burn,
#                   statn_all_burn) %>%
#   mutate(input_data = 'statn') %>%
#   mutate(year_missing_almost = gsub('statn_', '', cal)) %>%
#   mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
#   dplyr::select(-c(year_missing_almost))

statn_burn <- statn_all_burn %>%
  mutate(input_data = 'statn') %>%
  mutate(year_missing_almost = gsub('statn_', '', cal)) %>%
  mutate(year_missing = gsub('all', 'none', year_missing_almost)) %>%
  dplyr::select(-c(year_missing_almost))

burn_params <- bind_rows(grid_burn, statn_burn) %>%
  ungroup() %>%
  mutate(across(c(luca_a_rain:luca_soilDistMPSLPS), as.numeric)) %>%
  group_by(cal) %>%
  mutate(across(c(luca_a_rain:luca_soilDistMPSLPS), mean)) %>%
  filter(soilID == 22) %>%
  dplyr::select(-soilID) %>% 
  pivot_longer(!c(cal, input_data, year_missing), 
               names_to = 'params',
               values_to = 'value') %>% 
  mutate(params = str_remove(params, 'luca_')) %>%
  mutate(params = as.factor(params),
         burn = 'yes') 
  

```

```{r echo = FALSE, message = FALSE, warning = FALSE}

plot_burnparams <- function(param_name) {
  burn_params %>%
    filter(params == param_name) %>%
    ggplot(aes(y = value,
               x = year_missing,
               color = input_data)) +
    geom_point(size = 3) +
    ggtitle(param_name) +
    theme_bw()
}

name2 <- levels(burn_params$params)

lapply(name2, plot_burnparams)


```

## Combined parameters

The burned HRU parameters were averaged together.

```{r echo = FALSE, message = FALSE, warning = FALSE}
params2 <- params %>%
  mutate(burn = 'no') %>%
  filter(param %in% c('a_rain',
                        'a_snow',
                        'soilMaxInfSummer',
                        'soilMaxDPS',
                        'lagSurfaceRunoff',
                        'soilDistMPSLPS'))

params_combo <- bind_rows(params2,
                          burn_params %>%
                            rename(param = params))

#function to plot all params
plot_params <- function(param_name) {
  params_combo %>%
    filter(param == param_name) %>%
    ggplot(aes(x = year_missing,
               y = value,
               shape = burn, 
               color = input_data)) + 
    geom_point(size = 3) + 
    ggtitle(param_name) +
    theme_bw()
}

#name <- levels(params_combo$param)

lapply(name2, plot_params)


# boxplots of burned and unburned

# ggplot(params_combo, aes(x=burn, y=value, fill=input_data)) +
#   geom_boxplot() +
#   facet_wrap(~param, scales = 'free_y')
# 
# write_csv(params_combo, '/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/params_burn_unburn.csv')

```

## Parameters area weighted

```{r echo = FALSE, message = FALSE, warning = FALSE}

# add area weights to params combo
params_weighted <- params_combo %>%
  mutate(area = if_else(burn == 'no', 48243400,
                        18823000)) %>%
  group_by(param, cal) %>%
  summarize(numerator = sum(value * area),
    denominator = sum(area)) %>%
  mutate(area_weighted_average = numerator / denominator) %>%
  dplyr::select(-c(numerator, denominator)) %>%
  separate(col = cal, into = c("source", "year_missing"), sep = "_")
  
#write_csv(params_weighted, '/Users/megansears/Documents/Repos/fourmile/38HRU_sept2013_updates/params_weighted_sept2013_edits.csv')

#function to plot all params
plot_params <- function(param_name) {
  params_weighted %>%
    filter(param == param_name) %>%
    ggplot(aes(x = year_missing,
               y = area_weighted_average,
               color = source)) + 
    geom_point(size = 3) + 
    ggtitle(param_name) +
    theme_bw()
}

#name <- levels(params_combo$param)

lapply(name2, plot_params)

```